CREATE EXTERNAL TABLE '/tmp/puredata/alert/dropsession/result/drop_list.tsv'
USING (
    DELIMITER '\t'
    NULLVALUE ''
    DATEDELIM '/'
    ENCODING 'INTERNAL'
    ESCAPECHAR '\'
    TIMESTYLE '24HOUR'
    REMOTESOURCE 'JDBC'
    LOGDIR '/tmp/puredata/alert/dropsession/log'
) AS
SELECT
    EX_SESSIONID
    ,EX_START_DT
    ,EX_DBNAME
    ,EX_USERNAME
    ,EX_QUERY
    ,EX_RUNNING_DURATION
FROM 
    (
        SELECT
            Q.QS_SESSIONID AS EX_SESSIONID
            ,Q.QS_PLANID AS EX_PLANID
            ,Q.QS_CLIENTID AS EX_CLIENTID
            ,S.DBNAME AS EX_DBNAME
            ,S.USERNAME AS EX_USERNAME
            ,S.TYPE AS EX_SESSION_TYPE
            ,S.STATUS AS EX_SESSION_STATUS
            ,S.PRIORITY AS EX_SESSION_PRIORITY
            ,Q.QS_CLIIPADDR AS EX_CLIIPADDR
            ,Q.QS_STATE AS EX_STATE
            ,TRANSLATE(TRANSLATE(TRANSLATE(SUBSTR(Q.QS_SQL,1,200), CHR(10),' '), CHR(9),' '), '?', '') AS EX_QUERY
            ,CASE
                WHEN Q.QS_STATE = 1 THEN 'PENDING'
                WHEN Q.QS_STATE = 2 THEN 'QUEUED'
                WHEN Q.QS_STATE = 3 THEN 'RUNNING'
                WHEN Q.QS_STATE = 4 THEN 'ABORTED'
                WHEN Q.QS_STATE = 5 THEN 'DONE'
                ELSE 'UNKNOWN'
            END QS_STATE_DESCRIPTION
            ,Q.QS_TSUBMIT + INTERVAL '9 HOURS' AS EX_SUBMIT_DT
            ,Q.QS_TSTART + INTERVAL '9 HOURS' AS EX_START_DT
            ,EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - (S.CONNTIME::TIMESTAMP + INTERVAL '9 HOURS'))) AS EX_RUNNING_DURATION_1
            ,CASE
                WHEN Q.QS_TSTART = '1970-01-01 09:00:00'::TIMESTAMP THEN 0
                ELSE ABSTIME 'NOW' - Q.QS_TSTART
            END AS EX_RUNNING_DURATION
            ,Q.QS_PRITXT AS EX_PRITXT
            ,Q.QS_ESTCOST AS EX_ESTCOST
            ,Q.QS_ESTDISK AS EX_ESTDISK
            ,Q.QS_ESTMEM AS EX_ESTMEM
            ,Q.QS_SNIPPETS AS EX_SNIPPETS
            ,Q.QS_CURSNIPT AS EX_CURSNIPT
            ,Q.QS_RESROWS AS EX_RESROWS
            ,Q.QS_RESBYTES AS EX_RESBYTES
        FROM
            _V_QRYSTAT Q
            INNER JOIN _V_SESSION S ON Q.QS_SESSIONID = S.ID
    ) AS WITHDAMMY
WHERE
    EX_RUNNING_DURATION > 900
AND EX_USERNAME NOT IN ('ADMIN', 'ZOZO_CRM', 'ZOZO_KPIREPORT', 'ZOZO_REPORT', 'DIGDAG')

UNION ALL

SELECT
    SESSION_ID AS EX_SESSIONID
    ,SESSION_CONNTIME AS EX_START_DT
    ,SESSION_DBNAME AS EX_DBNAME
    ,SESSION_USERNAME AS EX_USERNAME
    ,SESSION_COMMAND AS EX_QUERY
    ,EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - (SESSION_CONNTIME::TIMESTAMP + INTERVAL '9 HOURS'))) AS EX_RUNNING_DURATION
FROM
    (
        SELECT 
            ID AS SESSION_ID
            ,PID AS SESSION_PID
            ,USERNAME AS SESSION_USERNAME
            ,DBNAME AS SESSION_DBNAME
            ,"TYPE" AS SESSION_TYPE
            ,CONNTIME::TIMESTAMP AS SESSION_CONNTIME
            ,STATUS AS SESSION_STATUS
            ,TRANSLATE(TRANSLATE(TRANSLATE(SUBSTR(COMMAND,1,200), CHR(10),' '), CHR(9),' '), '?', '') AS SESSION_COMMAND
            ,PRIORITY AS SESSION_PRIORITY
            ,CID AS SESSION_CID
            ,IPADDR AS SESSION_IPADDR
        FROM 
            _V_SESSION
    ) BASE
WHERE
    SESSION_STATUS = 'active'
AND SESSION_USERNAME NOT IN ('ADMIN', 'ZOZO_CRM', 'ZOZO_KPIREPORT', 'ZOZO_REPORT', 'DIGDAG')
AND (SESSION_CONNTIME::TIMESTAMP + INTERVAL '9 HOURS') <= CURRENT_TIMESTAMP + INTERVAL '-60 MINUTES'
;
