CREATE EXTERNAL TABLE '/tmp/puredata/alert/dropsession/result/drop_list.tsv'
USING (
    DELIMITER '\t'
    NULLVALUE ''
    DATEDELIM '/'
    ENCODING 'INTERNAL'
    ESCAPECHAR '\'
    TIMESTYLE '24HOUR'
    REMOTESOURCE 'JDBC'
    LOGDIR '/tmp/puredata/alert/dropsession/log'
) AS
SELECT
    EX_SESSIONID
    ,EX_START_DT
    ,EX_DBNAME
    ,EX_USERNAME
    ,EX_QUERY
    ,EX_RUNNING_DURATION
FROM (
    SELECT
        Q.QS_SESSIONID AS EX_SESSIONID,
        Q.QS_PLANID AS EX_PLANID,
        Q.QS_CLIENTID AS EX_CLIENTID,
        S.DBNAME AS EX_DBNAME,
        S.USERNAME AS EX_USERNAME,
        S.TYPE AS EX_SESSION_TYPE,
        S.STATUS AS EX_SESSION_STATUS,
        S.PRIORITY AS EX_SESSION_PRIORITY,
        Q.QS_CLIIPADDR AS EX_CLIIPADDR,
        Q.QS_STATE AS EX_STATE,
        TRANSLATE(TRANSLATE(TRANSLATE(SUBSTR(Q.QS_SQL,1,200), chr(10),' '), chr(9),' '), '?', '') AS EX_QUERY,
        CASE
            WHEN Q.QS_STATE = 1 THEN 'PENDING'
            WHEN Q.QS_STATE = 2 THEN 'QUEUED'
            WHEN Q.QS_STATE = 3 THEN 'RUNNING'
            WHEN Q.QS_STATE = 4 THEN 'ABORTED'
            WHEN Q.QS_STATE = 5 THEN 'DONE'
            ELSE 'UNKNOWN'
        END QS_STATE_DESCRIPTION,
        Q.QS_TSUBMIT + INTERVAL '9 HOUR' AS EX_SUBMIT_DT,
        Q.QS_TSTART + INTERVAL '9 HOUR' AS EX_START_DT,
        CASE
            WHEN Q.QS_TSTART = '1970-01-01 09:00:00'::TIMESTAMP THEN 0
            ELSE ABSTIME 'NOW' - Q.QS_TSTART
        END AS EX_RUNNING_DURATION,
        Q.QS_PRITXT AS EX_PRITXT,
        Q.QS_ESTCOST AS EX_ESTCOST,
        Q.QS_ESTDISK AS EX_ESTDISK,
        Q.QS_ESTMEM AS EX_ESTMEM,
        Q.QS_SNIPPETS AS EX_SNIPPETS,
        Q.QS_CURSNIPT AS EX_CURSNIPT,
        Q.QS_RESROWS AS EX_RESROWS,
        Q.QS_RESBYTES AS EX_RESBYTES
    FROM
        _V_QRYSTAT Q
    INNER JOIN _V_SESSION S ON Q.QS_SESSIONID = S.ID
) AS WITHDAMMY
WHERE
-- DEBUG
--     EX_USERNAME = 'SAITO'
-- PRODUCTION
    EX_RUNNING_DURATION > 900
AND EX_USERNAME NOT IN ('ADMIN', 'ZOZO_CRM', 'ZOZO_KPIREPORT', 'ZOZO_REPORT', 'DIGDAG')
ORDER BY
    EX_RUNNING_DURATION DESC
;
