CREATE TABLE TAT_VIACHANNEL_VISITUSER
(
    VC_VISITTIME TIMESTAMP,
    VC_SENDDT DATE,
    VC_CHANNEL BYTEINT,
    VC_CHANNEL_DETAIL BYTEINT,
    VC_CAMPAIGNID INTEGER,
    VC_DEVICE BYTEINT,
    VC_OS BYTEINT,
    VC_EMAILID BIGINT,
    VC_OFFERID BIGINT,
    VC_FULLVISITORID NVARCHAR(30),
    VC_TRANSACTIONREVENUE BIGINT
)
DISTRIBUTE ON (VC_VISITTIME, VC_CHANNEL, VC_CHANNEL_DETAIL, VC_CAMPAIGNID);

CREATE TABLE TAT_PARAMETERMAPPING
(
    PM_CHANNEL INTEGER,
    PM_CHANNEL_DETAIL INTEGER,
    PM_PARAMETER NVARCHAR(50),
    PM_MAPPINGID INTEGER
)
DISTRIBUTE ON (PM_CHANNEL, PM_CHANNEL_DETAIL, PM_PARAMETER);

CREATE TABLE TAT_CHANNELIDMASTER
(
    CM_CHANNEL INTEGER,
    CM_DEFINITION NVARCHAR(50)
)
DISTRIBUTE ON (CM_CHANNEL);

CREATE TABLE TAT_CHANNELDETAILIDMASTER	
(
    CDM_CHANNEL_DETAIL INTEGER,
    CDM_DEFINITION NVARCHAR(50)
)
DISTRIBUTE ON (CDM_CHANNEL_DETAIL);

