CREATE TABLE TAT_DB_HISTORY_VISIT_USER
(
    HVU_SENDDT DATE,
    HVU_CHANNELID BYTEINT NOT NULL,
    HVU_CHANNEL_DETAILID BYTEINT,
    HVU_CAMPAIGNID INTEGER NOT NULL,
    HVU_DEVICEID BYTEINT,
    HVU_OSID BYTEINT,
    HVU_FULLVISITORID VARCHAR(30),
    HVU_EMAILID BIGINT,
    HVU_OFFERID BIGINT,
    HVU_VISITTIME TIMESTAMP NOT NULL,
    HVU_REVENUE BIGINT
)
DISTRIBUTE ON (HVU_VISITTIME, HVU_CHANNELID, HVU_CHANNEL_DETAILID, HVU_CAMPAIGNID);

CREATE TABLE TAT_DB_MASTER_PARAMETER_MAPPING
(
    MPM_CHANNELID INTEGER NOT NULL,
    MPM_CHANNEL_DETAILID INTEGER,
    MPM_PARAMETER NVARCHAR(50) NOT NULL,
    MPM_MAPPINGID INTEGER NOT NULL
)
DISTRIBUTE ON (MPM_CHANNELID, MPM_CHANNEL_DETAILID, MPM_PARAMETER);

CREATE TABLE TAT_DB_MASTER_CHANNEL							
(
    MCH_CHANNELID INTEGER NOT NULL,
    MCH_CHANNELNAME NVARCHAR(50) NOT NULL
)
DISTRIBUTE ON (MCH_CHANNELID);

CREATE TABLE TAT_DB_MASTER_CHANNEL_DETAIL							
(
    MCD_CHANNEL_DETAILID INTEGER NOT NULL,
    MCD_CHANNEL_DETAILNAME NVARCHAR(50) NOT NULL
)
DISTRIBUTE ON (MCD_CHANNEL_DETAILID);

