CREATE TABLE TAT_HOURLY_SENDRESULTS
(
    HSR_HOUR BYTEINT NOT NULL,
    HSR_CHANNEL BYTEINT NOT NULL,
    HSR_CHANNEL_DETAIL BYTEINT,
    HSR_CAMPAIGNID INTEGER NOT NULL,
    HSR_DEVICE BYTEINT,
    HSR_OS BYTEINT,
    HSR_CNT_SEND INTEGER NOT NULL,
    HSR_CNT_OPEN INTEGER NOT NULL,
    HSR_CNT_CLICK INTEGER NOT NULL,
    HSR_CNT_BUYITEM SMALLINT NOT NULL
)
DISTRIBUTE ON (HSR_HOUR, HSR_CHANNEL, HSR_CHANNEL_DETAIL, HSR_CAMPAIGNID);