CREATE TABLE TAT_HOURLY_SENDRESULTS
(
    HSR_HOUR BYTEINT NOT NULL,
    HSR_CHANNELID BYTEINT NOT NULL,
    HSR_CHANNEL_DETAILID BYTEINT,
    HSR_CAMPAIGNID INTEGER NOT NULL,
    HSR_DEVICEID BYTEINT,
    HSR_OSID BYTEINT,
    HSR_CNT_SEND INTEGER NOT NULL,
    HSR_CNT_OPEN INTEGER NOT NULL,
    HSR_CNT_CLICK INTEGER NOT NULL,
    HSR_CNT_BUYITEM SMALLINT NOT NULL
)
DISTRIBUTE ON (HSR_HOUR, HSR_CHANNELID, HSR_CHANNEL_DETAILID, HSR_CAMPAIGNID);