--EMAILID取得
SELECT
    SENDDT
    ,SENDEMAILID
    ,TOPICSFLAG
    ,SUM(INTEGER(NVL(totals.totalTransactionRevenue/1000000, 0))) AS REVENUE
FROM (
    SELECT
        LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS SENDDT
        ,INTEGER(SUBSTR(TRAFFICSOURCE.CAMPAIGN, 13, LENGTH(TRAFFICSOURCE.CAMPAIGN) - (LENGTH(REGEXP_REPLACE(TRAFFICSOURCE.CAMPAIGN, R'^\d+', ''))+12))) AS SENDEMAILID--キャンペーンの値から日付+_以降の値を引く
        ,CASE WHEN REGEXP_MATCH(trafficSource.campaign,'^[0-9]{13,}_PC_03') THEN 1 ELSE 0 END AS TOPICSFLAG--ショップトピックス流入フラグ
        ,TOTALS.TOTALTRANSACTIONREVENUE
    FROM
        TABLE_DATE_RANGE([109049626.ga_sessions_],DATE_ADD(CURRENT_DATE(), -1, 'DAY'), DATE_ADD(CURRENT_DATE(), -1, 'DAY'))
    WHERE
        TRAFFICSOURCE.MEDIUM = 'mailmag'
        AND TRAFFICSOURCE.SOURCE = 'ni_m'
        AND SUBSTR(TRAFFICSOURCE.CAMPAIGN, 0, 8) = DATE --配信日のみの流入にしぼる
        AND REGEXP_MATCH(TRAFFICSOURCE.CAMPAIGN,'^[0-9]{13,}_PC')--PCのみの流入にしぼる（テスト対象がPCメールのみのため）
) AS BASE
GROUP BY
    SENDDT
    ,SENDEMAILID
    ,TOPICSFLAG
;