--ANDROID
SELECT
    2 AS OSID
    ,FULLVISITORID
FROM
    TABLE_DATE_RANGE([90303901.ga_sessions_], DATE_ADD(DATE_ADD(CURRENT_DATE(), -1, 'DAY'), -1, 'YEAR'), DATE_ADD(CURRENT_DATE(), -1, 'DAY'))
WHERE
    REGEXP_MATCH(HITS.APPINFO.SCREENNAME, R'^.*push_type=PUSH_(N|P|S)')
GROUP EACH BY
    FULLVISITORID
