--ANDROID
SELECT
    2 AS OSID
    ,FULLVISITORID
FROM
    TABLE_DATE_RANGE([90303901.ga_sessions_], DATE_ADD(DATE_ADD(CURRENT_DATE(), -1, 'DAY'), -1, 'YEAR'), DATE_ADD(CURRENT_DATE(), -1, 'DAY'))
GROUP EACH BY
    FULLVISITORID
