--WEBVIEW
SELECT
    CASE
        WHEN TRAFFICSOURCE.SOURCE = 'ios' THEN 1
        WHEN TRAFFICSOURCE.SOURCE = 'android' THEN 2
        ELSE NULL
    END AS OSID
    ,FULLVISITORID
FROM
    TABLE_DATE_RANGE([109049626.ga_sessions_], DATE_ADD(DATE_ADD(CURRENT_DATE(), -1, 'DAY'), -1, 'YEAR'), DATE_ADD(CURRENT_DATE(), -1, 'DAY'))
WHERE
    TRAFFICSOURCE.SOURCE IN ('ios', 'android')
    AND REGEXP_MATCH(TRAFFICSOURCE.CAMPAIGN, R'PUSH_M\d{3}.*')
GROUP EACH BY
    OSID
    ,FULLVISITORID