BEGIN;

CREATE TEMP TABLE IKKI_NEWARRIVALMAIL_DESIGNTEST_VISITMEMBER_20180531_TEMP
(
	SENDDT NATIONAL CHARACTER VARYING(8),
	SENDEMAILID INTEGER,
    TOPICSFLAG BYTEINT,
	REVENUE INTEGER
) DISTRIBUTE ON (SENDDT, SENDEMAILID, TOPICSFLAG)
;

INSERT INTO IKKI_NEWARRIVALMAIL_DESIGNTEST_VISITMEMBER_20180531_TEMP
SELECT
	SENDDT
	,SENDEMAILID
	,TOPICSFLAG
	,REVENUE
FROM
	EXTERNAL '${embulk.file_path}/${embulk.out_file}'
USING (DELIM ',' REMOTESOURCE 'JDBC' LOGDIR '/tmp/embulk/puredata/log')
;

DELETE FROM IKKI_NEWARRIVALMAIL_DESIGNTEST_VISITMEMBER_20180531
WHERE
    SENDDT BETWEEN (SELECT MIN(SENDDT) FROM IKKI_NEWARRIVALMAIL_DESIGNTEST_VISITMEMBER_20180531_TEMP) AND (SELECT MAX(SENDDT) FROM IKKI_NEWARRIVALMAIL_DESIGNTEST_VISITMEMBER_20180531_TEMP)
;

INSERT INTO IKKI_NEWARRIVALMAIL_DESIGNTEST_VISITMEMBER_20180531
SELECT
	SENDDT
	,SENDEMAILID
    ,TOPICSFLAG
	,REVENUE
FROM
	IKKI_NEWARRIVALMAIL_DESIGNTEST_VISITMEMBER_20180531_TEMP
;

COMMIT
;