BEGIN;

DELETE FROM TAT_DB_HISTORY_MAILMAG_USER WHERE HMU_DATE >= CURRENT_DATE AND HMU_DATE < CURRENT_DATE + INTERVAL '1DAY';

CREATE TEMP TABLE VALIDMEMBER_TEMP
(
    VALIDEMAILID INTEGER,
    VALIDTYPEID INTEGER
)
DISTRIBUTE ON (VALIDEMAILID, VALIDTYPEID);

CREATE TEMP TABLE ACTIVEMEMBER_TEMP
(
    ACTIVEEMAILID INTEGER,
    ACTIVETYPEID INTEGER
)
DISTRIBUTE ON (ACTIVEEMAILID, ACTIVETYPEID);

INSERT INTO VALIDMEMBER_TEMP
SELECT DISTINCT
    MMAEMAILID AS VALIDEMAILID
    ,MMATYPEID AS VALIDTYPEID
FROM
    VADMIN_MAILMAG
    INNER JOIN TMAILMAGAZINEALL ON MMEMAILID = MMAEMAILID
    LEFT OUTER JOIN VADMIN_TIDMEMBER ON MEMEMBERID = TIDMEMBERID
WHERE
    MMERRORCOUNT < 2
    AND MMEMAIL IS NOT NULL
    AND MEMEMBERID IS NOT NULL
    AND MMAMALLID = 1
    AND MMATYPEID IN (1, 1003, 1004)
    AND MMADELETEDT IS NULL
    AND TIDMEMBERID IS NULL;

INSERT INTO ACTIVEMEMBER_TEMP
SELECT DISTINCT
    EMAILID AS ACTIVEEMAILID
    ,CASE
        WHEN MMD.MAILMAGCAMPAIGNID NOT IN (9000, 9010) AND UPPER(CP.TYPENAME) NOT IN ('PA_M', 'CS_Q', 'PL_M')
            THEN 1
        WHEN MMD.MAILMAGCAMPAIGNID = 9000
            THEN 1003
        WHEN MMD.MAILMAGCAMPAIGNID = 9010
            THEN 1004
    END AS ACTIVETYPEID
FROM
    TUCMAILMAGDELIVERY AS MMD
    INNER JOIN TUCMAILMAGDELIVERYDETAIL AS MMDD ON MMD.ARTICLEID = MMDD.ARTICLEID
    INNER JOIN TUCMAILMAGCAMPAIGN AS CP ON MMD.MAILMAGCAMPAIGNID = CP.MAILMAGCAMPAIGNID
WHERE
    OPENDT >= CURRENT_DATE::TIMESTAMP + INTERVAL '-1YEAR'
    AND OPENDT < CURRENT_DATE::TIMESTAMP
    AND (
        (MMD.MAILMAGCAMPAIGNID NOT IN (9000, 9010) AND UPPER(CP.TYPENAME) NOT IN ('PA_M', 'CS_Q', 'PL_M'))
        OR
        MMD.MAILMAGCAMPAIGNID IN (9000, 9010)
    );

INSERT INTO TAT_DB_HISTORY_MAILMAG_USER
SELECT
    CURRENT_DATE AS HMU_DATE
    ,VALIDTYPEID AS HMU_TYPEID
    ,COUNT(DISTINCT VALIDEMAILID) AS HMU_VALIDEMAILCNT
    ,COUNT(CASE WHEN ACTIVEEMAILID IS NOT NULL THEN VALIDEMAILID ELSE NULL END) AS HMU_ACTIVEEMAILCNT
FROM
    VALIDMEMBER_TEMP
    LEFT OUTER JOIN ACTIVEMEMBER_TEMP ON VALIDEMAILID = ACTIVEEMAILID AND VALIDTYPEID = ACTIVETYPEID
GROUP BY
    VALIDTYPEID;

COMMIT;