BEGIN;

CREATE TEMP TABLE TAT_PUSHMEMBERHISTORY_TEMP
(
    OSID BYTEINT,
    FULLVISITORID VARCHAR(30)
)
DISTRIBUTE ON (OSID, FULLVISITORID);

INSERT INTO TAT_PUSHMEMBERHISTORY_TEMP
SELECT
	OSID
    ,FULLVISITORID
FROM
	EXTERNAL 'C:\Users\keiko\Documents\BQtoPD\TAT_PUSHMEMBERHISTORY_TEMP.csv'--digdagの環境にあわせ変更予定
--USING (DELIM ',' REMOTESOURCE 'JDBC' LOGDIR '/tmp/embulk/puredata/log'); -- skipRows 1
USING (DELIM ',' REMOTESOURCE 'ODBC' LOGDIR 'C:\Users\keiko\Documents\neteezalog' SKIPROWS 1);--ローカル用

DELETE FROM TAT_PUSHMEMBERHISTORY WHERE PMH_DATE >= CURRENT_DATE AND PMH_DATE < CURRENT_DATE + INTERVAL '1DAY';

INSERT INTO TAT_PUSHMEMBERHISTORY
SELECT
    VM_DATE AS PMH_DATE
    ,VM_OSID AS PMH_OSID
    ,VM_VALIDUSERCNT_PERSONAL AS PMH_VALIDUSERCNT_PERSONAL
    ,VM_VALIDUSERCNT_NEWARRIVAL_ONETIME AS PMH_VALIDUSERCNT_NEWARRIVAL_ONETIME
    ,VM_VALIDUSERCNT_NEWARRIVAL_REALTIME AS PMH_VALIDUSERCNT_NEWARRIVAL_REALTIME
    ,VM_VALIDUSERCNT_MASS AS PMH_VALIDUSERCNT_MASS
    ,AM_ACTIVEUSERCNT AS PMH_ACTIVEUSERCNT
FROM (
    SELECT
        CURRENT_DATE AS VM_DATE
        ,UU_TYPEID AS VM_OSID
        ,COUNT(DISTINCT CASE WHEN PNSPUSHTYPECATEGORYID = 1 THEN UU_MEMBERID ELSE NULL END) AS VM_VALIDUSERCNT_PERSONAL
        ,COUNT(DISTINCT CASE WHEN PNSPUSHTYPECATEGORYID = 2 THEN UU_MEMBERID ELSE NULL END) AS VM_VALIDUSERCNT_NEWARRIVAL_ONETIME
        ,COUNT(DISTINCT CASE WHEN PNSPUSHTYPECATEGORYID = 5 THEN UU_MEMBERID ELSE NULL END) AS VM_VALIDUSERCNT_NEWARRIVAL_REALTIME
        ,COUNT(DISTINCT CASE WHEN PNSPUSHTYPECATEGORYID = 6 THEN UU_MEMBERID ELSE NULL END) AS VM_VALIDUSERCNT_MASS
    FROM (
        SELECT
            PB_MEMBERID AS UU_MEMBERID
            ,PB_UID AS UU_UID
            ,PB_TYPEID AS UU_TYPEID
        FROM (
            SELECT
                PNMEMBERID AS PB_MEMBERID
                ,PNUID AS PB_UID
                ,PNDEVICETYPEID AS PB_TYPEID
                ,ROW_NUMBER() OVER (PARTITION BY PNMEMBERID ORDER BY PNMODIFYDT DESC) AS PB_NUMBER
            FROM
                TPUSHNOTIFICATION
            WHERE
                PNMEMBERID IS NOT NULL
				AND PNMODIFYDT < CURRENT_DATE::TIMESTAMP
        ) AS PUSHBASE/*PRFIX = PB*/
        WHERE
            PB_NUMBER = 1--最新のMODIFYDTのレコードを正とする
    ) AS UNIQUEUID/*PREFIX = UU*/
    INNER JOIN TPUSHNOTIFICATIONSETTING ON UU_UID = PNSUID
    WHERE
        PNSPUSHTYPECATEGORYID IN (1, 2, 5, 6)
        AND PNSDELETEFLAG = 0
    GROUP BY
        VM_OSID
) AS VALIDMEMBER /*PREFIX = VM*/
LEFT OUTER JOIN (
    SELECT
        CURRENT_DATE AS AM_DATE
        ,OSID AS AM_OSID
        ,COUNT(DISTINCT FULLVISITORID) AS AM_ACTIVEUSERCNT
    FROM
        TAT_PUSHMEMBERHISTORY_TEMP
    GROUP BY
        AM_OSID
) AS ACTIVEMEMBER /*PREFIX = AM*/ ON VM_DATE = AM_DATE AND VM_OSID = AM_OSID;

COMMIT;

