BEGIN
;

DELETE
FROM
    TAT_SITE_ACCESSDATA_LANDINGPAGE
WHERE
    SAL_MONTH < DATE_TRUNC('MONTH', CURRENT_DATE + INTERVAL '-2YEARS')::TIMESTAMP
    OR SAL_MONTH >= DATE_TRUNC('MONTH', CURRENT_DATE + INTERVAL '-1MONTH')::TIMESTAMP
;

INSERT INTO TAT_SITE_ACCESSDATA_LANDINGPAGE
SELECT
    SAL_MONTH::DATE,
    SAL_DEVICEID,
    SAL_PAGECATEGORYID,
    SAL_SOURCEID,
    SAL_CNT_USER,
    SAL_BOUNCERATE
FROM
    EXTERNAL '${embulk.file_path}/${embulk.out_file}'
USING (DELIM ',' REMOTESOURCE 'JDBC' LOGDIR '/tmp/embulk/puredata/log' MAXERRORS 0)
;

COMMIT
;
