wf:
  name: Sample Digdag Workflow using Pure & Bigquery

bq:
  dataset_name: temp
  table_name: digdag_export_sample
  destination: gs://stk-bigquery-export/digdag_export_sample_*.csv.gz
  query: queries/BQ/usermerge.sql

embulk:
  yml_path: embulk/gcs_fileload_guessed.yml
  file_path: /tmp/embulk/digdag_export_sample
  file_prefix: digdag_export_sample_
  out_file: loadfile_digdag_export_sample.csv # これはfile_prefixと被らないようにしないと消えちゃう
  key_file_path: /var/lib/digdag/.credential/gcpcredential.json

pure:
  jar: /var/lib/digdag/puredata/nzExecuteSql.jar
  class: jp.stk.cfm.ExecuteSqls
  query_dir: queries/DWH
  properties: /var/lib/digdag/puredata/dbconnection.properties

slack:
  webhook: https://hooks.slack.com/services/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
  channel: '#cfm_science_team'
  username: digdag
  icon_emoji: ghost
  template_path: notification
  good: good-template.yml
  danger: danger-template.yml
