BEGIN;

CREATE TEMP TABLE TBQ_MEASUREMENT_DEPRECATE_WEB_MEMBER_TEMP (
    MEMBERID INTEGER NOT NULL
)
DISTRIBUTE ON (MEMBERID);

INSERT INTO TBQ_MEASUREMENT_DEPRECATE_WEB_MEMBER_TEMP (
    MEMBERID
)
SELECT
    MEMBERID
FROM
    EXTERNAL '${embulk.file_path}/${embulk.out_file}'
USING (DELIM ',' REMOTESOURCE 'JDBC' LOGDIR '/tmp/embulk/puredata/log')
;

--運用時使用クエリ
TRUNCATE TABLE TBQ_MEASUREMENT_DEPRECATE_WEB_MEMBER
;

INSERT INTO TBQ_MEASUREMENT_DEPRECATE_WEB_MEMBER (
    MEMBERID
)
SELECT
    MEMBERID
FROM
    TBQ_MEASUREMENT_DEPRECATE_WEB_MEMBER_TEMP
;

COMMIT
;