BEGIN
;

DELETE
FROM
    TAT_SITE_ACCESSDATA_PAGE
WHERE
    SAP_MONTH < DATE_TRUNC('MONTH', CURRENT_DATE + INTERVAL '-2YEARS')::TIMESTAMP
    OR SAP_MONTH >= DATE_TRUNC('MONTH', CURRENT_DATE + INTERVAL '-1MONTH')::TIMESTAMP
;

INSERT INTO TAT_SITE_ACCESSDATA_PAGE
SELECT
    SAP_MONTH::DATE,
    SAP_DEVICEID,
    SAP_PAGECATEGORYID,
    SAP_CNT_USER,
    SAP_PV,
    SAP_BOUNCERATE,
    SAP_CVR
FROM
    EXTERNAL '${embulk.file_path}/${embulk.out_file}'
USING (DELIM ',' REMOTESOURCE 'JDBC' LOGDIR '/tmp/embulk/puredata/log' MAXERRORS 0)
;

COMMIT
;