SELECT
    STRFTIME_UTC_USEC(UTC_USEC_TO_MONTH(DT), "%Y/%m/%d") AS SAPR_MONTH
    ,DEVICE AS SAPR_DEVICEID
    ,PRICETYPEID AS SAPR_PRICETYPEID
    ,SUM(UU) AS SAPR_CNT_USER
FROM (
    --WEB
    SELECT
        STRFTIME_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000, "%Y/%m/%d") AS DT
        ,CASE WHEN REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*') IS FALSE THEN 1 ELSE 2 END AS DEVICE
        ,CASE WHEN REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/(sp/)*shop/[^/]+/goods/\d+/(\?|$)') THEN 1 ELSE 2 END AS PRICETYPEID--1:プロパー 2:セール
        ,EXACT_COUNT_DISTINCT(FULLVISITORID) AS UU
    FROM
        TABLE_DATE_RANGE([109049626.ga_sessions_],DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'MONTH'), DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'DAY'))
    WHERE
        TRAFFICSOURCE.SOURCE NOT IN ('ios', 'android')
        AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/app/') IS FALSE
        AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*\?app=1') IS FALSE
        AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/(sp/)*shop/[^/]+/goods(-sale)*/\d+/(\?|$)') --goodsページに限定
    GROUP EACH BY
        DT
        ,DEVICE
        ,PRICETYPEID
),
(
    --APP
    SELECT
        STRFTIME_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000, "%Y/%m/%d") AS DT
        ,3 AS DEVICE
        ,CASE WHEN REGEXP_MATCH(HITS.APPINFO.SCREENNAME, R'^[^/]+/goods/\d+/(\?|$)') THEN 1 ELSE 2 END AS PRICETYPEID--1:プロパー 2:セール
        ,EXACT_COUNT_DISTINCT(FULLVISITORID) AS UU
    FROM
        TABLE_DATE_RANGE([90402834.ga_sessions_],DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'MONTH'), DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'DAY'))--iOS
        ,TABLE_DATE_RANGE([90303901.ga_sessions_],DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'MONTH'), DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'DAY'))--Android
    WHERE
        REGEXP_MATCH(HITS.APPINFO.SCREENNAME, R'^[^/]+/goods(-sale)*/\d+/(\?|$)')--goods
    GROUP EACH BY
        DT
        ,DEVICE
        ,PRICETYPEID
)
GROUP EACH BY
    SAPR_MONTH
    ,SAPR_DEVICEID
    ,SAPR_PRICETYPEID