BEGIN;

CREATE TEMP TABLE TAT_VIACHANNEL_VISITUSER_TEMP
(
    VC_VISITTIME TIMESTAMP,
    VC_SENDDT DATE,
    VC_CHANNEL BYTEINT,
    VC_CHANNEL_DETAIL BYTEINT,
    VC_CAMPAIGNID INTEGER,
    VC_DEVICE BYTEINT,
    VC_OS BYTEINT,
    VC_EMAILID BIGINT,
    VC_OFFERID BIGINT,
    VC_FULLVISITORID NVARCHAR(30),
    VC_TRANSACTIONREVENUE BIGINT
)
DISTRIBUTE ON (VC_VISITTIME, VC_CHANNEL, VC_CHANNEL_DETAIL, VC_CAMPAIGNID);

INSERT INTO TAT_VIACHANNEL_VISITUSER_TEMP
SELECT
    VC_VISITTIME
    ,VC_SENDDT::DATE
    ,VC_CHANNEL
    ,VC_CHANNEL_DETAIL
    ,VC_CAMPAIGNID
    ,VC_DEVICE
    ,VC_OS
    ,VC_EMAILID
    ,VC_OFFERID
    ,VC_FULLVISITORID
    ,VC_TRANSACTIONREVENUE
FROM
	EXTERNAL '/tmp/embulk/cfmdashboard_getvisituser/CFMDashboard_GetVisitUser.csv'
USING (DELIM ',' REMOTESOURCE 'JDBC' LOGDIR '/tmp/embulk/puredata/log');

DELETE FROM TAT_VIACHANNEL_VISITUSER
WHERE
    (VC_VISITTIME >= (SELECT MIN(VC_VISITTIME) FROM TAT_VIACHANNEL_VISITUSER_TEMP)
    AND VC_VISITTIME < (SELECT MAX(VC_VISITTIME)  + INTERVAL'1 SECOND' FROM TAT_VIACHANNEL_VISITUSER_TEMP))
    OR VC_VISITTIME < CURRENT_DATE - INTERVAL'2 YEARS';

INSERT INTO TAT_VIACHANNEL_VISITUSER
SELECT
    VC_VISITTIME
    ,VC_SENDDT::DATE
    ,VC_CHANNEL
    ,VC_CHANNEL_DETAIL
    ,VC_CAMPAIGNID
    ,VC_DEVICE
    ,VC_OS
    ,VC_EMAILID
    ,VC_OFFERID
    ,VC_FULLVISITORID
    ,VC_TRANSACTIONREVENUE
FROM
	TAT_VIACHANNEL_VISITUSER_TEMP;

COMMIT;