BEGIN;

CREATE TEMP TABLE TAT_VIACHANNEL_VISITUSER_TEMP
(
    VC_VISITTIME TIMESTAMP,
    VC_SENDDT DATE,
    VC_CHANNELID BYTEINT,
    VC_CHANNEL_DETAILID BYTEINT,
    VC_CAMPAIGNID INTEGER,
    VC_DEVICEID BYTEINT,
    VC_OSID BYTEINT,
    VC_EMAILID BIGINT,
    VC_OFFERID BIGINT,
    VC_FULLVISITORID NVARCHAR(30),
    VC_TRANSACTIONREVENUE BIGINT
)
DISTRIBUTE ON (VC_VISITTIME, VC_CHANNELID, VC_CHANNEL_DETAILID, VC_CAMPAIGNID);

INSERT INTO TAT_VIACHANNEL_VISITUSER_TEMP
SELECT
    VC_VISITTIME
    ,VC_SENDDT::DATE
    ,VC_CHANNELID
    ,VC_CHANNEL_DETAILID
    ,VC_CAMPAIGNID
    ,VC_DEVICEID
    ,VC_OSID
    ,VC_EMAILID
    ,VC_OFFERID
    ,VC_FULLVISITORID
    ,VC_TRANSACTIONREVENUE
FROM
	EXTERNAL '/tmp/embulk/cfmdashboard_getvisituser/CFMDashboard_GetVisitUser.csv'
USING (DELIM ',' REMOTESOURCE 'JDBC' LOGDIR '/tmp/embulk/puredata/log');

DELETE FROM TAT_VIACHANNEL_VISITUSER
WHERE
    VC_VISITTIME BETWEEN (SELECT MIN(VC_VISITTIME) FROM TAT_VIACHANNEL_VISITUSER_TEMP) AND (SELECT MAX(VC_VISITTIME) FROM TAT_VIACHANNEL_VISITUSER_TEMP)
    OR VC_VISITTIME < CURRENT_DATE - INTERVAL'2 YEARS';

INSERT INTO TAT_VIACHANNEL_VISITUSER
SELECT
    VC_VISITTIME
    ,VC_SENDDT::DATE
    ,VC_CHANNELID
    ,VC_CHANNEL_DETAILID
    ,VC_CAMPAIGNID
    ,VC_DEVICEID
    ,VC_OSID
    ,VC_EMAILID
    ,VC_OFFERID
    ,VC_FULLVISITORID
    ,VC_TRANSACTIONREVENUE
FROM
	TAT_VIACHANNEL_VISITUSER_TEMP;

COMMIT;