SELECT
    DT AS SUT_DT
    ,DEVICEID AS SUT_DEVICEID
    ,MEMBERID AS SUT_MEMBERID
    ,UID AS SUT_UID
FROM (
    --WEB
    SELECT
        STRFTIME_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000, "%Y/%m/%d") AS DT
        ,CASE WHEN REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo.jp/sp/.*') IS FALSE THEN 1 ELSE 2 END AS DEVICEID
        ,HITS.CUSTOMVARIABLES.CUSTOMVARVALUE AS MEMBERID
    FROM
        TABLE_DATE_RANGE([109049626.ga_sessions_],DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'MONTH'), DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'DAY'))
    WHERE
        TRAFFICSOURCE.SOURCE NOT IN ('ios', 'android')
        AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/app/') IS FALSE
        AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*\?app=1') IS FALSE
        AND REGEXP_MATCH(HITS.CUSTOMVARIABLES.CUSTOMVARNAME, R'(memberId|memberID)')
        AND REGEXP_MATCH(HITS.CUSTOMVARIABLES.CUSTOMVARVALUE, R'^[0-9]{1,}')
        AND REGEXP_MATCH(HITS.CUSTOMVARIABLES.CUSTOMVARVALUE, R'%') IS FALSE
    GROUP EACH BY
        DT
        ,DEVICEID
        ,MEMBERID
),
(
    --APP
    SELECT
        STRFTIME_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000, "%Y/%m/%d") AS DT
        ,3 AS DEVICEID
        ,HITS.CUSTOMDIMENSIONS.VALUE AS UID
    FROM
        TABLE_DATE_RANGE([90402834.ga_sessions_],DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'MONTH'), DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'DAY'))--iOS
        ,TABLE_DATE_RANGE([90303901.ga_sessions_],DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'MONTH'), DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'DAY'))--Android
    WHERE
        HITS.CUSTOMDIMENSIONS.INDEX = 2
    GROUP EACH BY
        DT
        ,DEVICEID
        ,UID
)