SELECT
    STRFTIME_UTC_USEC(UTC_USEC_TO_MONTH(DT), "%Y/%m/%d") AS SUN_MONTH
    ,DEVICEID AS SUN_DEVICEID
    ,NEWVISITFLAG AS SUN_NEWVISITFLAG
    ,SUM(UU) AS SUN_CNT_USER
FROM (
    --WEB
    SELECT
        STRFTIME_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000, "%Y/%m/%d") AS DT
        ,CASE WHEN REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*') IS FALSE THEN 1 ELSE 2 END AS DEVICEID
        ,NVL(TOTALS.NEWVISITS, 0) AS NEWVISITFLAG
        ,EXACT_COUNT_DISTINCT(FULLVISITORID) AS UU
    FROM
        TABLE_DATE_RANGE([109049626.ga_sessions_],DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'MONTH'), DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'DAY'))
    WHERE
        TRAFFICSOURCE.SOURCE NOT IN ('ios', 'android')
        AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/app/') IS FALSE
        AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*\?app=1') IS FALSE
        AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/')
    GROUP EACH BY
        DT
        ,DEVICEID
        ,NEWVISITFLAG
),
(
    --APP
    SELECT
        STRFTIME_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000, "%Y/%m/%d") AS DT
        ,3 AS DEVICEID
        ,NVL(TOTALS.NEWVISITS, 0) AS NEWVISITFLAG
        ,EXACT_COUNT_DISTINCT(FULLVISITORID) AS UU
    FROM
        TABLE_DATE_RANGE([90402834.ga_sessions_],DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'MONTH'), DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'DAY'))--iOS
        ,TABLE_DATE_RANGE([90303901.ga_sessions_],DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'MONTH'), DATE_ADD(TIMESTAMP(FORMAT_UTC_USEC(UTC_USEC_TO_MONTH(NOW()))), -1, 'DAY'))--Android
    GROUP EACH BY
        DT
        ,DEVICEID
        ,NEWVISITFLAG
)
GROUP EACH BY
    SUN_MONTH
    ,SUN_DEVICEID
    ,SUN_NEWVISITFLAG