BEGIN;

CREATE TEMP TABLE TBQ_MEASUREMENT_DEPRECATE_APP_DEVICEINFO_TEMP (
    VISITSTARTDT TIMESTAMP NOT NULL,
    UID CHARACTER VARYING(100) NOT NULL,
    DEVICE_INFO CHARACTER VARYING(100),
    DEVICE_MOBILEDEVICEMODEL CHARACTER VARYING(50),
    DEVICE_OS CHARACTER VARYING(50)
)
DISTRIBUTE ON (UID);

INSERT INTO TBQ_MEASUREMENT_DEPRECATE_APP_DEVICEINFO_TEMP (
    VISITSTARTDT
    ,UID
    ,DEVICE_INFO
    ,DEVICE_MOBILEDEVICEMODEL
    ,DEVICE_OS
)
SELECT
    VISITSTARTDT
    ,UID
    ,DEVICE_INFO
    ,DEVICE_MOBILEDEVICEMODEL
    ,DEVICE_OS
FROM
    EXTERNAL '${embulk.file_path}/${embulk.out_file}'
USING (DELIM ',' REMOTESOURCE 'JDBC' LOGDIR '/tmp/embulk/puredata/log')
;

--運用時使用クエリ
TRUNCATE TABLE TBQ_MEASUREMENT_DEPRECATE_APP_DEVICEINFO
;

INSERT INTO TBQ_MEASUREMENT_DEPRECATE_APP_DEVICEINFO (
    VISITSTARTDT
    ,UID
    ,DEVICE_INFO
    ,DEVICE_MOBILEDEVICEMODEL
    ,DEVICE_OS
)
SELECT
    VISITSTARTDT
    ,UID
    ,DEVICE_INFO
    ,DEVICE_MOBILEDEVICEMODEL
    ,DEVICE_OS
FROM
    TBQ_MEASUREMENT_DEPRECATE_APP_DEVICEINFO_TEMP
;

COMMIT
;