SELECT
    CASE
        WHEN REGEXP_MATCH(HVU_SENDDT, R'^[0-9]{8}')
            THEN STRFTIME_UTC_USEC(HVU_SENDDT, "%Y/%m/%d")
        ELSE NULL
    END AS HVU_SENDDT
    ,HVU_CHANNELID
    ,HVU_CHANNEL_DETAILID
    ,HVU_CAMPAIGNID
    ,NULL AS HVU_DEVICEID
    ,NULL AS HVU_OSID
    ,HVU_FULLVISITORID
    ,NULL AS HVU_EMAILID
    ,HVU_OFFERID
    ,STRFTIME_UTC_USEC(HVU_VISITTIME, "%Y/%m/%d %H:%M:%S") AS HVU_VISITTIME
    ,HVU_REVENUE
FROM
    --LINE_マス
    (
    SELECT
        LM_VISITTIME AS HVU_VISITTIME
        ,LM_SENDDT AS HVU_SENDDT
        ,MPM_CHANNELID AS HVU_CHANNELID
        ,MPM_CHANNEL_DETAILID AS HVU_CHANNEL_DETAILID
        ,MPM_MAPPINGID AS HVU_CAMPAIGNID
        ,LM_FULLVISITORID AS HVU_FULLVISITORID
        ,SUM(INTEGER(NVL(LM_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LM_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS LM_SENDDT
            ,TRAFFICSOURCE.SOURCE AS LM_SOURCE
            ,FULLVISITORID AS LM_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LM_REVENUE
            ,DATE AS LM_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
    ) AS LINE_MASS/*PREFIX = LM*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING] AS MAPPING_TABLE ON LM_SOURCE = MPM_PARAMETER
    WHERE
        MPM_CHANNELID = 2--LINE
        AND MPM_CHANNEL_DETAILID = 2--マス
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_FULLVISITORID
    ),
    --LINE_パーソナライズ_2.0
    (
    SELECT
        LPO_VISITTIME AS HVU_VISITTIME
        ,LPO_SENDDT AS HVU_SENDDT
        ,MPM_CHANNELID AS HVU_CHANNELID
        ,MPM_CHANNEL_DETAILID AS HVU_CHANNEL_DETAILID
        ,MPM_MAPPINGID AS HVU_CAMPAIGNID
        ,LPO_FULLVISITORID AS HVU_FULLVISITORID
        ,SUM(INTEGER(NVL(LPO_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LPO_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS LPO_SENDDT
            ,NTH(3, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS LPO_SOURCE
            ,FULLVISITORID AS LPO_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LPO_REVENUE
            ,DATE AS LPO_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.MEDIUM = 'linepersonal'
            AND LENGTH(TRAFFICSOURCE.CAMPAIGN) <= 12--2.0はOFFERIDがついていないので
    ) AS LINE_PERSONALIZE_OLD/*PREFIX = LPO*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING] AS MAPPING_TABLE ON LPO_SOURCE = MPM_PARAMETER
    WHERE
        MPM_CHANNELID = 2--LINE
        AND MPM_CHANNEL_DETAILID = 4--パーソナライズ
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_FULLVISITORID
    ),
    --LINE_パーソナライズ_3.0
    (
    SELECT
        LPN_VISITTIME AS HVU_VISITTIME
        ,LPN_SENDDT AS HVU_SENDDT
        ,2 AS HVU_CHANNELID--LINE
        ,4 AS HVU_CHANNEL_DETAILID--パーソナライズ
        ,INTEGER(LPN_CAMPAIGNID) AS HVU_CAMPAIGNID
        ,CASE
            WHEN REGEXP_MATCH(LPN_OFFERID, R'^[0-9]{1,}')
                THEN INTEGER(LPN_OFFERID)
            ELSE NULL
        END AS HVU_OFFERID
        ,LPN_FULLVISITORID AS HVU_FULLVISITORID
        ,SUM(INTEGER(NVL(LPN_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LPN_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS LPN_SENDDT
            ,NTH(3, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS LPN_CAMPAIGNID
            ,NTH(2, SPLIT(TRAFFICSOURCE.CAMPAIGN, '_')) AS LPN_OFFERID
            ,FULLVISITORID AS LPN_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LPN_REVENUE
            ,DATE AS LPN_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.MEDIUM = 'linepersonal'
    ) AS LINE_PERSONALIZE_NEW/*PREFIX = LPN*/
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_OFFERID
        ,HVU_FULLVISITORID
    ),
    --LINE_タイムライン
    (
    SELECT
        LT_VISITTIME AS HVU_VISITTIME
        ,LT_SENDDT AS HVU_SENDDT
        ,MPM_CHANNELID AS HVU_CHANNELID
        ,MPM_CHANNEL_DETAILID AS HVU_CHANNEL_DETAILID
        ,MPM_MAPPINGID AS HVU_CAMPAIGNID
        ,LT_FULLVISITORID AS HVU_FULLVISITORID
        ,SUM(INTEGER(NVL(LT_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LT_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS LT_SENDDT
            ,TRAFFICSOURCE.SOURCE AS LT_SOURCE
            ,FULLVISITORID AS LT_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LT_REVENUE
            ,DATE AS LT_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
    ) AS LINE_TIMELINE/*PREFIX = LT*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING] AS MAPPING_TABLE ON LT_SOURCE = MPM_PARAMETER
    WHERE
        MPM_CHANNELID = 2--LINE
        AND MPM_CHANNEL_DETAILID = 5--タイムライン
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_FULLVISITORID
    ),
    --LINE_リッチメニュー
    (
    SELECT
        LR_VISITTIME AS HVU_VISITTIME
        ,MPM_CHANNELID AS HVU_CHANNELID
        ,MPM_CHANNEL_DETAILID AS HVU_CHANNEL_DETAILID
        ,MPM_MAPPINGID AS HVU_CAMPAIGNID
        ,LR_FULLVISITORID AS HVU_FULLVISITORID
        ,SUM(INTEGER(NVL(LR_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LR_VISITTIME
            ,TRAFFICSOURCE.SOURCE AS LR_SOURCE
            ,FULLVISITORID AS LR_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LR_REVENUE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
    ) AS LINE_RICHMENU/*PREFIX = LR*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING] AS MAPPING_TABLE ON LR_SOURCE = MPM_PARAMETER
    WHERE
        MPM_CHANNELID = 2--LINE
        AND MPM_CHANNEL_DETAILID = 6--リッチメニュー
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_FULLVISITORID
    )