SELECT
    CASE
        WHEN REGEXP_MATCH(HVU_SENDDT, R'^[0-9]{8}')
            THEN STRFTIME_UTC_USEC(HVU_SENDDT, "%Y/%m/%d")
        ELSE NULL
    END AS HVU_SENDDT
    ,HVU_CHANNELID
    ,HVU_CHANNEL_DETAILID
    ,HVU_CAMPAIGNID
    ,HVU_DEVICEID
    ,NULL AS HVU_OSID
    ,HVU_FULLVISITORID
    ,NULL AS HVU_EMAILID
    ,HVU_OFFERID
    ,STRFTIME_UTC_USEC(HVU_VISITTIME, "%Y/%m/%d %H:%M:%S") AS HVU_VISITTIME
    ,HVU_FULLVISITORID_CV
    ,HVU_REVENUE
FROM
    --Pメール_2.0
    (
    SELECT
        AD_VISITTIME AS HVU_VISITTIME
        ,AD_SENDDT AS HVU_SENDDT
        ,AD_CHANNELID AS HVU_CHANNELID
        ,AD_CHANNEL_DETAILID AS HVU_CHANNEL_DETAILID
        ,AD_CAMPAIGNID AS HVU_CAMPAIGNID
        ,CASE
            WHEN AD_DEVICE = 'MO' THEN 1
            WHEN AD_DEVICE = 'PC' THEN 2
            ELSE 99
        END AS HVU_DEVICEID
        ,AD_FULLVISITORID AS HVU_FULLVISITORID
        ,CASE WHEN CD_FULLVISITORID IS NOT NULL THEN AD_FULLVISITORID ELSE NULL END AS HVU_FULLVISITORID_CV
        ,SUM(INTEGER(NVL(AD_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            MPO_VISITTIME AS AD_VISITTIME
            ,MPO_SENDDT AS AD_SENDDT
            ,MPM_CHANNELID AS AD_CHANNELID
            ,MPM_CHANNEL_DETAILID AS AD_CHANNEL_DETAILID
            ,MPM_MAPPINGID AS AD_CAMPAIGNID
            ,MPO_DEVICE AS AD_DEVICE
            ,MPO_FULLVISITORID AS AD_FULLVISITORID
            ,MPO_VISITID AS AD_VISITID
            ,MPO_REVENUE AS AD_REVENUE
        FROM (
            SELECT
                MPOB_VISITTIME AS MPO_VISITTIME
                ,MPOB_SENDDT AS MPO_SENDDT
                ,LEFT(MPOB_SOURCE, 10) AS MPO_SOURCE
                ,LEFT(MPOB_DEVICE, 2) AS MPO_DEVICE
                ,MPOB_FULLVISITORID AS MPO_FULLVISITORID
                ,MPOB_VISITID AS MPO_VISITID
                ,MPOB_REVENUE AS MPO_REVENUE
            FROM (
                SELECT
                    FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS MPOB_VISITTIME
                    ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS MPOB_SENDDT
                    ,NTH(3, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS MPOB_SOURCE
                    ,NTH(5, SPLIT(UPPER(TRAFFICSOURCE.SOURCE), '_')) AS MPOB_DEVICE
                    ,FULLVISITORID AS MPOB_FULLVISITORID
                    ,TOTALS.TOTALTRANSACTIONREVENUE AS MPOB_REVENUE
                    ,VISITID AS MPOB_VISITID
                FROM
                    TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
                    ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
                WHERE
                    TRAFFICSOURCE.MEDIUM = 'mailpersonal'
            ) AS MAIL_PERSONALIZE_OLD_BASE/*PREFIX = MPOB*/
        ) AS MAIL_PERSONALIZE_OLD/*PREFIX = MPO*/
        INNER JOIN [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING] AS MAPPING_TABLE ON MPO_SOURCE = MPM_PARAMETER
        WHERE
            MPM_CHANNELID = 1--メール
            AND MPM_CHANNEL_DETAILID = 4--パーソナライズ
    ) AS ACCESSDATA/*PREFIX=AD*/
    LEFT OUTER JOIN (
        SELECT
            FULLVISITORID AS CD_FULLVISITORID
            ,VISITID AS CD_VISITID
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.SOURCE NOT IN ('ios', 'android')
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/app/') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*\?app=1') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/(sp/)*_cart/(order/|shopping/)arigato\.html') --ARIGATOページ
        GROUP EACH BY
            CD_FULLVISITORID
            ,CD_VISITID
    ) AS CVDATA /*PREFIX=CD*/ ON AD_FULLVISITORID = CD_FULLVISITORID AND AD_VISITID = CD_VISITID
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_DEVICEID
        ,HVU_FULLVISITORID
        ,HVU_FULLVISITORID_CV
    ),
    --Pメール_3.0
    (
    SELECT
        MPN_VISITTIME AS HVU_VISITTIME
        ,MPN_SENDDT AS HVU_SENDDT
        ,1 AS HVU_CHANNELID--メール
        ,4 AS HVU_CHANNEL_DETAILID--パーソナライズ
        ,INTEGER(MPN_CAMPAIGNID) AS HVU_CAMPAIGNID
        ,CASE
            WHEN MPN_DEVICE IN ('1', '2')
                THEN INTEGER(MPN_DEVICE)
            ELSE 99
        END AS HVU_DEVICEID
        ,CASE
            WHEN REGEXP_MATCH(MPN_OFFERID, R'^[0-9]{1,}')
                THEN INTEGER(MPN_OFFERID)
            ELSE NULL
        END AS HVU_OFFERID
        ,MPN_FULLVISITORID AS HVU_FULLVISITORID
        ,CASE WHEN CD_FULLVISITORID IS NOT NULL THEN MPN_FULLVISITORID ELSE NULL END AS HVU_FULLVISITORID_CV
        ,SUM(INTEGER(NVL(MPN_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            MPNB_VISITTIME AS MPN_VISITTIME
            ,MPNB_SENDDT AS MPN_SENDDT
            ,MPNB_CAMPAIGNID AS MPN_CAMPAIGNID
            ,MPNB_DEVICE AS MPN_DEVICE
            ,MPNB_OFFERID AS MPN_OFFERID
            ,MPNB_FULLVISITORID AS MPN_FULLVISITORID
            ,MPNB_REVENUE AS MPN_REVENUE
            ,MPNB_VISITID AS MPN_VISITID
        FROM (
            SELECT
                FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS MPNB_VISITTIME
                ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS MPNB_SENDDT
                ,NTH(3, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS MPNB_CAMPAIGNID
                ,NTH(4, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS MPNB_DEVICE
                ,NTH(2, SPLIT(TRAFFICSOURCE.CAMPAIGN, '_')) AS MPNB_OFFERID
                ,FULLVISITORID AS MPNB_FULLVISITORID
                ,TOTALS.TOTALTRANSACTIONREVENUE AS MPNB_REVENUE
                ,VISITID AS MPNB_VISITID
            FROM
                TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
                ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            WHERE
                TRAFFICSOURCE.MEDIUM = 'mailpersonal'
        ) AS MAIL_PERSONALIZE_NEW_BASE/*PREFIX = MPNB*/
        LEFT OUTER JOIN (
            SELECT
                MPM_PARAMETER
            FROM
                [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING]
            WHERE
                MPM_CHANNELID = 1
                AND MPM_CHANNEL_DETAILID = 4
        ) AS MAPPING_TABLE ON MPNB_CAMPAIGNID = MPM_PARAMETER
        WHERE
            MPM_PARAMETER IS NULL
    ) AS MAIL_PERSONALIZE_NEW/*PREFIX = MPN*/
    LEFT OUTER JOIN (
        SELECT
            FULLVISITORID AS CD_FULLVISITORID
            ,VISITID AS CD_VISITID
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.SOURCE NOT IN ('ios', 'android')
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/app/') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*\?app=1') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/(sp/)*_cart/(order/|shopping/)arigato\.html') --ARIGATOページ
        GROUP EACH BY
            CD_FULLVISITORID
            ,CD_VISITID
    ) AS CVDATA /*PREFIX=CD*/ ON MPN_FULLVISITORID = CD_FULLVISITORID AND MPN_VISITID = CD_VISITID
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_DEVICEID
        ,HVU_OFFERID
        ,HVU_FULLVISITORID
        ,HVU_FULLVISITORID_CV
    ),
    --トランザクションメール
    (
    SELECT
        AD_VISITTIME AS HVU_VISITTIME
        ,AD_SENDDT AS HVU_SENDDT
        ,AD_CHANNELID AS HVU_CHANNELID
        ,AD_CHANNEL_DETAILID AS HVU_CHANNEL_DETAILID
        ,AD_CAMPAIGNID AS HVU_CAMPAIGNID
        ,AD_FULLVISITORID AS HVU_FULLVISITORID
        ,CASE WHEN CD_FULLVISITORID IS NOT NULL THEN AD_FULLVISITORID ELSE NULL END AS HVU_FULLVISITORID_CV
        ,SUM(INTEGER(NVL(AD_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            MT_VISITTIME AS AD_VISITTIME
            ,MT_SENDDT AS AD_SENDDT
            ,MPM_CHANNELID AS AD_CHANNELID
            ,MPM_CHANNEL_DETAILID AS AD_CHANNEL_DETAILID
            ,MPM_MAPPINGID AS AD_CAMPAIGNID
            ,MT_FULLVISITORID AS AD_FULLVISITORID
            ,MT_VISITID AS AD_VISITID
            ,MT_REVENUE AS AD_REVENUE
        FROM (
            SELECT
                FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS MT_VISITTIME
                ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS MT_SENDDT
                ,TRAFFICSOURCE.SOURCE AS MT_SOURCE
                ,FULLVISITORID AS MT_FULLVISITORID
                ,TOTALS.TOTALTRANSACTIONREVENUE AS MT_REVENUE
                ,VISITID AS MT_VISITID
            FROM
                TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
                ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        ) AS MAIL_TRANSACTION/*PREFIX = MT*/
        INNER JOIN [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING] AS MAPPING_TABLE ON MT_SOURCE = MPM_PARAMETER
        WHERE
            MPM_CHANNELID = 1--メール
            AND MPM_CHANNEL_DETAILID = 3--トランザクション
    ) AS ACCESSDATA/*PREFIX=AD*/
    LEFT OUTER JOIN (
        SELECT
            FULLVISITORID AS CD_FULLVISITORID
            ,VISITID AS CD_VISITID
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.SOURCE NOT IN ('ios', 'android')
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/app/') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*\?app=1') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/(sp/)*_cart/(order/|shopping/)arigato\.html') --ARIGATOページ
        GROUP EACH BY
            CD_FULLVISITORID
            ,CD_VISITID
    ) AS CVDATA /*PREFIX=CD*/ ON AD_FULLVISITORID = CD_FULLVISITORID AND AD_VISITID = CD_VISITID
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_FULLVISITORID
        ,HVU_FULLVISITORID_CV
    )