SELECT
    CASE
        WHEN REGEXP_MATCH(HVU_SENDDT, R'^[0-9]{8}')
            THEN STRFTIME_UTC_USEC(HVU_SENDDT, "%Y/%m/%d")
        ELSE NULL
    END AS HVU_SENDDT
    ,HVU_CHANNELID
    ,HVU_CHANNEL_DETAILID
    ,HVU_CAMPAIGNID
    ,HVU_DEVICEID
    ,NULL AS HVU_OSID
    ,HVU_FULLVISITORID
    ,HVU_EMAILID
    ,NULL AS HVU_OFFERID
    ,STRFTIME_UTC_USEC(HVU_VISITTIME, "%Y/%m/%d %H:%M:%S") AS HVU_VISITTIME
    ,HVU_FULLVISITORID_CV
    ,HVU_REVENUE
FROM
    --新着(TOWN)
    (
    SELECT
        AD_VISITTIME AS HVU_VISITTIME
        ,AD_SENDDT AS HVU_SENDDT
        ,AD_CHANNELID AS HVU_CHANNELID
        ,AD_CHANNEL_DETAILID AS HVU_CHANNEL_DETAILID
        ,AD_CAMPAIGNID AS HVU_CAMPAIGNID
        ,CASE
            WHEN AD_DEVICE = 'MO' THEN 1
            WHEN AD_DEVICE = 'PC' THEN 2
            ELSE 99
         END AS HVU_DEVICEID
        ,CASE
            WHEN REGEXP_MATCH(AD_EMAILID, R'^[0-9]{1,}')
                THEN INTEGER(AD_EMAILID)
            ELSE NULL
        END AS HVU_EMAILID--新着メルマガは過去EMAILIDがついていなかった時期があるためNULLを除く条件は入れられない
        ,AD_FULLVISITORID AS HVU_FULLVISITORID
        ,CASE WHEN CD_FULLVISITORID IS NOT NULL THEN AD_FULLVISITORID ELSE NULL END AS HVU_FULLVISITORID_CV
        ,SUM(INTEGER(NVL(AD_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            MNT_VISITTIME AS AD_VISITTIME
            ,MNT_SENDDT AS AD_SENDDT
            ,MNT_SOURCE AS AD_SOURCE
            ,MNT_DEVICE AS AD_DEVICE
            ,MNT_EMAILID AS AD_EMAILID
            ,MPM_CHANNELID AS AD_CHANNELID
            ,MPM_CHANNEL_DETAILID AS AD_CHANNEL_DETAILID
            ,MPM_MAPPINGID AS AD_CAMPAIGNID
            ,MNT_FULLVISITORID AS AD_FULLVISITORID
            ,MNT_VISITID AS AD_VISITID
            ,MNT_REVENUE AS AD_REVENUE
        FROM (
            SELECT
                MNTB_VISITTIME AS MNT_VISITTIME
                ,MNTB_SENDDT AS MNT_SENDDT
                ,MNTB_SOURCE AS MNT_SOURCE
                ,LEFT(MNTB_DEVICE, 2) AS MNT_DEVICE
                ,SUBSTR(MNTB_EMAILID, 13) AS MNT_EMAILID
                ,MNTB_FULLVISITORID AS MNT_FULLVISITORID
                ,MNTB_VISITID AS MNT_VISITID
                ,MNTB_REVENUE AS MNT_REVENUE
            FROM (
                SELECT
                    FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS MNTB_VISITTIME
                    ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS MNTB_SENDDT
                    ,TRAFFICSOURCE.SOURCE AS MNTB_SOURCE
                    ,NTH(2, SPLIT(UPPER(TRAFFICSOURCE.CAMPAIGN), '_')) AS MNTB_DEVICE
                    ,NTH(1, SPLIT(TRAFFICSOURCE.CAMPAIGN, '_')) AS MNTB_EMAILID
                    ,FULLVISITORID AS MNTB_FULLVISITORID
                    ,TOTALS.TOTALTRANSACTIONREVENUE AS MNTB_REVENUE
                    ,VISITID AS MNTB_VISITID
                FROM
                    TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
                    ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
                WHERE
                    TRAFFICSOURCE.MEDIUM = 'mailmag'
                    AND TRAFFICSOURCE.SOURCE = 'ni_m'--CHANNELIDとCHANNELDETAILIDではTOWN/USEDの区別がつかないためベタ書き
            ) AS MAIL_NEWARRIVAL_TOWN_BASE/*PREFIX = MNTB*/
        ) AS MAIL_NEWARRIVAL_TOWN/*PREFIX = MNT*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING] AS MAPPING_TABLE ON MNT_SOURCE = MPM_PARAMETER
    ) AS ACCESSDATA/*PREFIX=AD*/
    LEFT OUTER JOIN (
        SELECT
            FULLVISITORID AS CD_FULLVISITORID
            ,VISITID AS CD_VISITID
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.SOURCE NOT IN ('ios', 'android')
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/app/') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*\?app=1') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/(sp/)*_cart/(order/|shopping/)arigato\.html') --ARIGATOページ
        GROUP EACH BY
            CD_FULLVISITORID
            ,CD_VISITID
    ) AS CVDATA /*PREFIX=CD*/ ON AD_FULLVISITORID = CD_FULLVISITORID AND AD_VISITID = CD_VISITID
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_DEVICEID
        ,HVU_EMAILID
        ,HVU_FULLVISITORID
        ,HVU_FULLVISITORID_CV
    )