SELECT
    CASE
        WHEN REGEXP_MATCH(HVU_SENDDT, R'^[0-9]{8}')
            THEN STRFTIME_UTC_USEC(HVU_SENDDT, "%Y/%m/%d")
        ELSE NULL
    END AS HVU_SENDDT
    ,HVU_CHANNELID
    ,HVU_CHANNEL_DETAILID
    ,HVU_CAMPAIGNID
    ,HVU_DEVICEID
    ,NULL AS HVU_OSID
    ,HVU_FULLVISITORID
    ,HVU_EMAILID
    ,NULL AS HVU_OFFERID
    ,STRFTIME_UTC_USEC(HVU_VISITTIME, "%Y/%m/%d %H:%M:%S") AS HVU_VISITTIME
    ,HVU_REVENUE
FROM
    --新着(USED)
    (
    SELECT
        MNU_VISITTIME AS HVU_VISITTIME
        ,MNU_SENDDT AS HVU_SENDDT
        ,MPM_CHANNELID AS HVU_CHANNELID
        ,MPM_CHANNEL_DETAILID AS HVU_CHANNEL_DETAILID
        ,MPM_MAPPINGID AS HVU_CAMPAIGNID
        ,CASE
            WHEN MNU_DEVICE = 'MO' THEN 1
            WHEN MNU_DEVICE = 'PC' THEN 2
            ELSE 99
        END AS HVU_DEVICEID
        ,CASE
            WHEN REGEXP_MATCH(MNU_EMAILID, R'^[0-9]{1,}')
                THEN INTEGER(MNU_EMAILID)
            ELSE NULL
        END AS HVU_EMAILID--新着メルマガは過去EMAILIDがついていなかった時期があるためNULLを除く条件は入れられない
        ,MNU_FULLVISITORID AS HVU_FULLVISITORID
        ,SUM(INTEGER(NVL(MNU_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            MNUB_VISITTIME AS MNU_VISITTIME
            ,MNUB_SENDDT AS MNU_SENDDT
            ,MNUB_SOURCE AS MNU_SOURCE
            ,LEFT(MNUB_DEVICE, 2) AS MNU_DEVICE
            ,SUBSTR(MNUB_EMAILID, 13) AS MNU_EMAILID
            ,MNUB_FULLVISITORID AS MNU_FULLVISITORID
            ,MNUB_REVENUE AS MNU_REVENUE
            ,MNUB_DATE AS MNU_DATE
        FROM (
            SELECT
                FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS MNUB_VISITTIME
                ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS MNUB_SENDDT
                ,TRAFFICSOURCE.SOURCE AS MNUB_SOURCE
                ,NTH(2, SPLIT(UPPER(TRAFFICSOURCE.CAMPAIGN), '_')) AS MNUB_DEVICE
                ,NTH(1, SPLIT(TRAFFICSOURCE.CAMPAIGN, '_')) AS MNUB_EMAILID
                ,FULLVISITORID AS MNUB_FULLVISITORID
                ,TOTALS.TOTALTRANSACTIONREVENUE AS MNUB_REVENUE
                ,DATE AS MNUB_DATE
            FROM
                TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            WHERE
                TRAFFICSOURCE.MEDIUM = 'mailmag'
                AND TRAFFICSOURCE.SOURCE = 'ni_u_m'--CHANNELIDとCHANNELDETAILIDではTOWN/USEDの区別がつかないためベタ書き
        ) AS MAIL_NEWARRIVAL_USED_BASE/*PREFIX = MNU*/
    ) AS MAIL_NEWARRIVAL_USED/*PREFIX = MNU*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING] AS MAPPING_TABLE ON MNU_SOURCE = MPM_PARAMETER
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_DEVICEID
        ,HVU_EMAILID
        ,HVU_FULLVISITORID
    )