SELECT
    CASE
        WHEN REGEXP_MATCH(HVU_SENDDT, R'^[0-9]{8}')
            THEN STRFTIME_UTC_USEC(HVU_SENDDT, "%Y/%m/%d")
        ELSE NULL
    END AS HVU_SENDDT
    ,HVU_CHANNELID
    ,HVU_CHANNEL_DETAILID
    ,HVU_CAMPAIGNID
    ,HVU_DEVICEID
    ,NULL AS HVU_OSID
    ,HVU_FULLVISITORID
    ,HVU_EMAILID
    ,NULL AS HVU_OFFERID
    ,STRFTIME_UTC_USEC(HVU_VISITTIME, "%Y/%m/%d %H:%M:%S") AS HVU_VISITTIME
    ,HVU_FULLVISITORID_CV
    ,HVU_REVENUE
FROM
    --新着(USED)
    (
    SELECT
        AD_VISITTIME AS HVU_VISITTIME
        ,AD_SENDDT AS HVU_SENDDT
        ,AD_CHANNELID AS HVU_CHANNELID
        ,AD_CHANNEL_DETAILID AS HVU_CHANNEL_DETAILID
        ,AD_CAMPAIGNID AS HVU_CAMPAIGNID
        ,CASE
            WHEN AD_DEVICE = 'MO' THEN 1
            WHEN AD_DEVICE = 'PC' THEN 2
            ELSE 99
        END AS HVU_DEVICEID
        ,CASE
            WHEN REGEXP_MATCH(AD_EMAILID, R'^[0-9]{1,}')
                THEN INTEGER(AD_EMAILID)
            ELSE NULL
        END AS HVU_EMAILID--新着メルマガは過去EMAILIDがついていなかった時期があるためNULLを除く条件は入れられない
        ,AD_FULLVISITORID AS HVU_FULLVISITORID
        ,CASE WHEN CD_FULLVISITORID IS NOT NULL THEN AD_FULLVISITORID ELSE NULL END AS HVU_FULLVISITORID_CV
        ,SUM(INTEGER(NVL(AD_REVENUE/1000000, 0))) AS HVU_REVENUE
    FROM (
        SELECT
            MNU_VISITTIME AS AD_VISITTIME
            ,MNU_SENDDT AS AD_SENDDT
            ,MNU_SOURCE AS AD_SOURCE
            ,MNU_DEVICE AS AD_DEVICE
            ,MNU_EMAILID AS AD_EMAILID
            ,MPM_CHANNELID AS AD_CHANNELID
            ,MPM_CHANNEL_DETAILID AS AD_CHANNEL_DETAILID
            ,MPM_MAPPINGID AS AD_CAMPAIGNID
            ,MNU_FULLVISITORID AS AD_FULLVISITORID
            ,MNU_VISITID AS AD_VISITID
            ,MNU_REVENUE AS AD_REVENUE
        FROM (
            SELECT
                MNUB_VISITTIME AS MNU_VISITTIME
                ,MNUB_SENDDT AS MNU_SENDDT
                ,MNUB_SOURCE AS MNU_SOURCE
                ,LEFT(MNUB_DEVICE, 2) AS MNU_DEVICE
                ,SUBSTR(MNUB_EMAILID, 13) AS MNU_EMAILID
                ,MNUB_FULLVISITORID AS MNU_FULLVISITORID
                ,MNUB_VISITID AS MNU_VISITID
                ,MNUB_REVENUE AS MNU_REVENUE
            FROM (
                SELECT
                    FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS MNUB_VISITTIME
                    ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS MNUB_SENDDT
                    ,TRAFFICSOURCE.SOURCE AS MNUB_SOURCE
                    ,NTH(2, SPLIT(UPPER(TRAFFICSOURCE.CAMPAIGN), '_')) AS MNUB_DEVICE
                    ,NTH(1, SPLIT(TRAFFICSOURCE.CAMPAIGN, '_')) AS MNUB_EMAILID
                    ,FULLVISITORID AS MNUB_FULLVISITORID
                    ,TOTALS.TOTALTRANSACTIONREVENUE AS MNUB_REVENUE
                    ,VISITID AS MNUB_VISITID
                FROM
                    TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
                    ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
                WHERE
                    TRAFFICSOURCE.MEDIUM = 'mailmag'
                    AND TRAFFICSOURCE.SOURCE = 'ni_u_m'--CHANNELIDとCHANNELDETAILIDではTOWN/USEDの区別がつかないためベタ書き
            ) AS MAIL_NEWARRIVAL_USED_BASE/*PREFIX = MNUB*/
        ) AS MAIL_NEWARRIVAL_USED/*PREFIX = MNU*/
        INNER JOIN [durable-binder-547:ZZ_CFM.TAT_DB_MASTER_PARAMETER_MAPPING] AS MAPPING_TABLE ON MNU_SOURCE = MPM_PARAMETER
    ) AS ACCESSDATA/*PREFIX=AD*/
    LEFT OUTER JOIN (
        SELECT
            FULLVISITORID AS CD_FULLVISITORID
            ,VISITID AS CD_VISITID
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            ,TABLE_DATE_RANGE([89629218.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.SOURCE NOT IN ('ios', 'android')
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/app/') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/sp/.*\?app=1') IS FALSE
            AND REGEXP_MATCH(HITS.PAGE.PAGEPATH, R'^zozo\.jp/(sp/)*_cart/(order/|shopping/)arigato\.html') --ARIGATOページ
        GROUP EACH BY
            CD_FULLVISITORID
            ,CD_VISITID
    ) AS CVDATA /*PREFIX=CD*/ ON AD_FULLVISITORID = CD_FULLVISITORID AND AD_VISITID = CD_VISITID
    GROUP EACH BY
        HVU_VISITTIME
        ,HVU_SENDDT
        ,HVU_CHANNELID
        ,HVU_CHANNEL_DETAILID
        ,HVU_CAMPAIGNID
        ,HVU_DEVICEID
        ,HVU_EMAILID
        ,HVU_FULLVISITORID
        ,HVU_FULLVISITORID_CV
    )