BEGIN
;

DELETE
FROM
    TAT_SITE_USERATTRIBUTE_NEWVISITS
WHERE
    SUN_MONTH < DATE_TRUNC('MONTH', CURRENT_DATE + INTERVAL '-2YEARS')::TIMESTAMP
    OR SUN_MONTH >= DATE_TRUNC('MONTH', CURRENT_DATE + INTERVAL '-1MONTH')::TIMESTAMP
;

INSERT INTO TAT_SITE_USERATTRIBUTE_NEWVISITS
SELECT
    SUN_MONTH,
    SUN_DEVICEID,
    SUN_NEWVISITFLAG,
    SUN_CNT_USER
FROM
	EXTERNAL '${embulk.file_path1}/${embulk.out_file1}'
USING (DELIM ',' REMOTESOURCE 'JDBC' LOGDIR '/tmp/embulk/puredata/log' MAXERRORS 0)
;

COMMIT
;