SELECT
    STRFTIME_UTC_USEC(VC_VISITTIME, "%Y/%m/%d %H:%M:%S") AS VC_VISITTIME
    ,STRFTIME_UTC_USEC(VC_SENDDT, "%Y/%m/%d") AS VC_SENDDT
    ,VC_CHANNELID
    ,VC_CHANNEL_DETAILID
    ,VC_CAMPAIGNID
    ,NULL AS VC_DEVICEID
    ,NULL AS VC_OSID
    ,NULL AS VC_EMAILID
    ,VC_OFFERID
    ,VC_FULLVISITORID
    ,VC_REVENUE
FROM
    --LINE_マス
    (
    SELECT
        LM_VISITTIME AS VC_VISITTIME
        ,LM_SENDDT AS VC_SENDDT
        ,PM_CHANNELID AS VC_CHANNELID
        ,PM_CHANNEL_DETAILID AS VC_CHANNEL_DETAILID
        ,PM_MAPPINGID AS VC_CAMPAIGNID
        ,LM_FULLVISITORID AS VC_FULLVISITORID
        ,SUM(INTEGER(NVL(LM_REVENUE/1000000, 0))) AS VC_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LM_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS LM_SENDDT
            ,TRAFFICSOURCE.SOURCE AS LM_SOURCE
            ,FULLVISITORID AS LM_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LM_REVENUE
            ,DATE AS LM_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
    ) AS LINE_MASS/*PREFIX = LM*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_PARAMETERMAPPING] AS MAPPING_TABLE ON LM_SOURCE = PM_PARAMETER
    WHERE
        DATEDIFF(LM_DATE, LM_SENDDT) >= 0
        AND DATEDIFF(LM_DATE, LM_SENDDT) <= 7--配信から7日以内の流入に絞る
        AND PM_CHANNELID = 2--LINE
        AND PM_CHANNEL_DETAILID = 2--マス
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNELID
        ,VC_CHANNEL_DETAILID
        ,VC_CAMPAIGNID
        ,VC_FULLVISITORID
    ),
    --LINE_パーソナライズ_2.0
    (
    SELECT
        LPO_VISITTIME AS VC_VISITTIME
        ,LPO_SENDDT AS VC_SENDDT
        ,PM_CHANNELID AS VC_CHANNELID
        ,PM_CHANNEL_DETAILID AS VC_CHANNEL_DETAILID
        ,PM_MAPPINGID AS VC_CAMPAIGNID
        ,LPO_FULLVISITORID AS VC_FULLVISITORID
        ,SUM(INTEGER(NVL(LPO_REVENUE/1000000, 0))) AS VC_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LPO_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS LPO_SENDDT
            ,NTH(3, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS LPO_SOURCE
            ,FULLVISITORID AS LPO_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LPO_REVENUE
            ,DATE AS LPO_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.MEDIUM = 'linepersonal'
            AND LENGTH(TRAFFICSOURCE.CAMPAIGN) <= 12--2.0はOFFERIDがついていないので
    ) AS LINE_PERSONALIZE_OLD/*PREFIX = LPO*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_PARAMETERMAPPING] AS MAPPING_TABLE ON LPO_SOURCE = PM_PARAMETER
    WHERE
        DATEDIFF(LPO_DATE, LPO_SENDDT) >= 0
        AND DATEDIFF(LPO_DATE, LPO_SENDDT) <= 7--配信から7日以内の流入に絞る
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNELID
        ,VC_CHANNEL_DETAILID
        ,VC_CAMPAIGNID
        ,VC_FULLVISITORID
    ),
    --LINE_パーソナライズ_3.0
    (
    SELECT
        LPN_VISITTIME AS VC_VISITTIME
        ,LPN_SENDDT AS VC_SENDDT
        ,2 AS VC_CHANNELID--LINE
        ,4 AS VC_CHANNEL_DETAILID--パーソナライズ
        ,INTEGER(LPN_CAMPAIGNID) AS VC_CAMPAIGNID
        ,INTEGER(LPN_OFFERID) AS VC_OFFERID
        ,LPN_FULLVISITORID AS VC_FULLVISITORID
        ,SUM(INTEGER(NVL(LPN_REVENUE/1000000, 0))) AS VC_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LPN_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS LPN_SENDDT
            ,NTH(3, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS LPN_CAMPAIGNID
            ,NTH(2, SPLIT(TRAFFICSOURCE.CAMPAIGN, '_')) AS LPN_OFFERID
            ,FULLVISITORID AS LPN_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LPN_REVENUE
            ,DATE AS LPN_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.MEDIUM = 'linepersonal'
    ) AS LINE_PERSONALIZE_NEW/*PREFIX = LPN*/
    WHERE
        REGEXP_MATCH(LPN_OFFERID, R'^[0-9]{1,}')
        AND DATEDIFF(LPN_DATE, LPN_SENDDT) >= 0
        AND DATEDIFF(LPN_DATE, LPN_SENDDT) <= 7--配信から7日以内の流入に絞る
        AND INTEGER(LPN_CAMPAIGNID) IS NOT NULL
        AND INTEGER(LPN_OFFERID) IS NOT NULL
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNELID
        ,VC_CHANNEL_DETAILID
        ,VC_CAMPAIGNID
        ,VC_OFFERID
        ,VC_FULLVISITORID
    ),
    --LINE_タイムライン
    (
    SELECT
        LT_VISITTIME AS VC_VISITTIME
        ,LT_SENDDT AS VC_SENDDT
        ,PM_CHANNELID AS VC_CHANNELID
        ,PM_CHANNEL_DETAILID AS VC_CHANNEL_DETAILID
        ,PM_MAPPINGID AS VC_CAMPAIGNID
        ,LT_FULLVISITORID AS VC_FULLVISITORID
        ,SUM(INTEGER(NVL(LT_REVENUE/1000000, 0))) AS VC_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LT_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS LT_SENDDT
            ,TRAFFICSOURCE.SOURCE AS LT_SOURCE
            ,FULLVISITORID AS LT_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LT_REVENUE
            ,DATE AS LT_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
    ) AS LINE_TIMELINE/*PREFIX = LT*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_PARAMETERMAPPING] AS MAPPING_TABLE ON LT_SOURCE = PM_PARAMETER
    WHERE
        DATEDIFF(LT_DATE, LT_SENDDT) >= 0
        AND DATEDIFF(LT_DATE, LT_SENDDT) <= 7--配信から7日以内の流入に絞る
        AND PM_CHANNELID = 2--LINE
        AND PM_CHANNEL_DETAILID = 5--タイムライン
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNELID
        ,VC_CHANNEL_DETAILID
        ,VC_CAMPAIGNID
        ,VC_FULLVISITORID
    ),
    --LINE_リッチメニュー
    (
    SELECT
        LR_VISITTIME AS VC_VISITTIME
        ,PM_CHANNELID AS VC_CHANNELID
        ,PM_CHANNEL_DETAILID AS VC_CHANNEL_DETAILID
        ,PM_MAPPINGID AS VC_CAMPAIGNID
        ,LR_FULLVISITORID AS VC_FULLVISITORID
        ,SUM(INTEGER(NVL(LR_REVENUE/1000000, 0))) AS VC_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS LR_VISITTIME
            ,TRAFFICSOURCE.SOURCE AS LR_SOURCE
            ,FULLVISITORID AS LR_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS LR_REVENUE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
    ) AS LINE_RICHMENU/*PREFIX = LR*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_PARAMETERMAPPING] AS MAPPING_TABLE ON LR_SOURCE = PM_PARAMETER
    WHERE
        PM_CHANNELID = 2--LINE
        AND PM_CHANNEL_DETAILID = 6--リッチメニュー
    GROUP EACH BY
        VC_VISITTIME
        ,VC_CHANNELID
        ,VC_CHANNEL_DETAILID
        ,VC_CAMPAIGNID
        ,VC_FULLVISITORID
    )