SELECT
    STRFTIME_UTC_USEC(VC_VISITTIME, "%Y/%m/%d %H:%M:%S") AS VC_VISITTIME
    ,STRFTIME_UTC_USEC(VC_SENDDT, "%Y/%m/%d") AS VC_SENDDT
    ,VC_CHANNELID
    ,VC_CHANNEL_DETAILID
    ,VC_CAMPAIGNID
    ,NULL AS VC_DEVICEID
    ,VC_OSID
    ,NULL AS VC_EMAILID
    ,NULL AS VC_OFFERID
    ,VC_FULLVISITORID
    ,VC_REVENUE
FROM
    --PUSHウェブビュー(ウェブビュー遷移のマス:流入及び収益取得/その他：収益のみ取得）
    (
    SELECT
        PW_VISITTIME AS VC_VISITTIME
        ,PW_SENDDT AS VC_SENDDT
        ,3 AS VC_CHANNELID--PUSH
        ,CASE
            WHEN PW_CAMPAIGNFLAG = 1 THEN PM_CHANNEL_DETAILID
            WHEN PW_CAMPAIGNFLAG = 2 THEN 4--パーソナライズ
        END AS VC_CHANNEL_DETAILID
        ,CASE
            WHEN PW_CAMPAIGNFLAG = 1 THEN PM_MAPPINGID
            WHEN PW_CAMPAIGNFLAG = 2 THEN INTEGER(PW_CAMPAIGNID)
        END AS VC_CAMPAIGNID
        ,PW_OS AS VC_OSID
        ,PW_FULLVISITORID AS VC_FULLVISITORID
        ,SUM(INTEGER(NVL(PW_REVENUE/1000000, 0))) AS VC_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS PW_VISITTIME
            ,NTH(4, SPLIT(REGEXP_REPLACE(TRAFFICSOURCE.CAMPAIGN, R'^.*-', ''), '_')) AS PW_SENDDT
            ,CASE
                WHEN REGEXP_MATCH(TRAFFICSOURCE.CAMPAIGN, R'PUSH_(M|S|N)\d{3}.*') THEN 1--パーソナライズ以外
                WHEN REGEXP_MATCH(TRAFFICSOURCE.CAMPAIGN, R'PUSH_P\d{3}.*') THEN 2--パーソナライズ
            END AS PW_CAMPAIGNFLAG
            ,CASE
                WHEN REGEXP_MATCH(TRAFFICSOURCE.CAMPAIGN, R'PUSH_(M|S|N)\d{3}.*')
                    THEN CONCAT(NTH(2, SPLIT(REGEXP_REPLACE(TRAFFICSOURCE.CAMPAIGN, R'^.*-', ''), '_')),'_',NTH(3,SPLIT(REGEXP_REPLACE(TRAFFICSOURCE.CAMPAIGN, R'^.*-', ''), '_')) )
                WHEN REGEXP_MATCH(TRAFFICSOURCE.CAMPAIGN, R'PUSH_P\d{3}.*')
                    THEN NTH(1, SPLIT(REGEXP_REPLACE(TRAFFICSOURCE.CAMPAIGN, R'^.*PUSH_P', ''), '_'))
                ELSE NULL
            END AS PW_CAMPAIGNID
            ,CASE
                WHEN TRAFFICSOURCE.SOURCE = 'ios' THEN 1
                WHEN TRAFFICSOURCE.SOURCE = 'android' THEN 2
            END AS PW_OS
            ,CASE
                WHEN REGEXP_MATCH(TRAFFICSOURCE.CAMPAIGN, R'PUSH_M\d{3}.*') THEN FULLVISITORID
                ELSE NULL
            END AS PW_FULLVISITORID--ウェブビュー遷移のマスPUSHのみFULLVISITORIDを取得、それ以外は収益のみの取得
            ,TOTALS.TOTALTRANSACTIONREVENUE AS PW_REVENUE
            ,DATE AS PW_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.SOURCE IN ('ios', 'android')
            AND REGEXP_MATCH(TRAFFICSOURCE.CAMPAIGN, R'PUSH_(M|S|N|P)\d{3}.*')
    )AS PUSH_WEBVIEW/*PREFIX = PW*/
    LEFT OUTER JOIN [durable-binder-547:ZZ_CFM.TAT_PARAMETERMAPPING] AS MAPPING_TABLE ON PW_CAMPAIGNID = PM_PARAMETER--パーソナライズPUSHはマッピングテーブルとJOINできないのでLEFT JOIN
    WHERE
        DATEDIFF(PW_DATE, PW_SENDDT) >= 0
        AND DATEDIFF(PW_DATE, PW_SENDDT) <= 7--配信から7日以内の流入に絞る
        AND (PM_MAPPINGID IS NOT NULL OR INTEGER(PW_CAMPAIGNID) IS NOT NULL)
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNELID
        ,VC_CHANNEL_DETAILID
        ,VC_CAMPAIGNID
        ,VC_OSID
        ,VC_FULLVISITORID
    ),
    --マスPUSH_ネイティブ
    (
    SELECT
        PMN_VISITTIME AS VC_VISITTIME
        ,PMN_SENDDT AS VC_SENDDT
        ,PM_CHANNELID AS VC_CHANNELID
        ,PM_CHANNEL_DETAILID AS VC_CHANNEL_DETAILID
        ,PM_MAPPINGID AS VC_CAMPAIGNID
        ,PMN_OS AS VC_OSID
        ,PMN_FULLVISITORID AS VC_FULLVISITORID
    FROM (
        SELECT
            PMN_VISITTIME
            ,PMN_SENDDT
            ,PMN_CAMPAIGNID
            ,PMN_OS
            ,PMN_FULLVISITORID
            ,PMN_DATE
        FROM
            --PUSH_MASS_NATIVE/*PREFIX = PMN*/
            --iOS
            (SELECT
                FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS PMN_VISITTIME
                ,NTH(3, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')) AS PMN_SENDDT
                ,CONCAT(NTH(1, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')), '_', NTH(2, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_'))) AS PMN_CAMPAIGNID
                ,1 AS PMN_OS
                ,FULLVISITORID AS PMN_FULLVISITORID
                ,DATE AS PMN_DATE
            FROM
                TABLE_DATE_RANGE([90402834.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            WHERE
                REGEXP_MATCH(hits.appInfo.screenName, R'^.*push_type=PUSH_S')),
            --Android
            (SELECT
                FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS PMN_VISITTIME
                ,NTH(3, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')) AS PMN_SENDDT
                ,CONCAT(NTH(1, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')), '_', NTH(2, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_'))) AS PMN_CAMPAIGNID
                ,2 AS PMN_OS
                ,FULLVISITORID AS PMN_FULLVISITORID
                ,DATE AS PMN_DATE
            FROM
                TABLE_DATE_RANGE([90303901.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            WHERE
                REGEXP_MATCH(hits.appInfo.screenName, R'^.*push_type=PUSH_S')),
    ) AS VISIT
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_PARAMETERMAPPING] AS MAPPING_TABLE ON PMN_CAMPAIGNID = PM_PARAMETER
    WHERE
        DATEDIFF(PMN_DATE, PMN_SENDDT) >= 0
        AND DATEDIFF(PMN_DATE, PMN_SENDDT) <= 7--配信から7日以内の流入に絞る
        AND PM_CHANNELID = 3--PUSH
        AND PM_CHANNEL_DETAILID = 2--マス
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNELID
        ,VC_CHANNEL_DETAILID
        ,VC_CAMPAIGNID
        ,VC_OSID
        ,VC_FULLVISITORID
    ),
    --新着PUSH（おまとめ/リアルタイム）
    (
    SELECT
        PN_VISITTIME AS VC_VISITTIME
        ,PN_SENDDT AS VC_SENDDT
        ,PM_CHANNELID AS VC_CHANNELID
        ,PM_CHANNEL_DETAILID AS VC_CHANNEL_DETAILID
        ,PM_MAPPINGID AS VC_CAMPAIGNID
        ,PN_OS AS VC_OSID
        ,PN_FULLVISITORID AS VC_FULLVISITORID
    FROM (
        SELECT
            PN_VISITTIME
            ,PN_SENDDT
            ,PN_CAMPAIGNID
            ,PN_OS
            ,PN_FULLVISITORID
            ,PN_DATE
        FROM
            --PUSH_NEWARRIVAL/*PREFIX = PN*/
            --iOS
            (SELECT
                FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS PN_VISITTIME
                ,NTH(3, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')) AS PN_SENDDT
                ,CONCAT(NTH(1, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')), '_', NTH(2, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_'))) AS PN_CAMPAIGNID
                ,1 AS PN_OS
                ,FULLVISITORID AS PN_FULLVISITORID
                ,DATE AS PN_DATE
            FROM
                TABLE_DATE_RANGE([90402834.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            WHERE
                REGEXP_MATCH(hits.appInfo.screenName, R'^.*push_type=PUSH_N')),
            --Android
            (SELECT
                FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS PN_VISITTIME
                ,NTH(3, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')) AS PN_SENDDT
                ,CONCAT(NTH(1, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')), '_', NTH(2, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_'))) AS PN_CAMPAIGNID
                ,2 AS PN_OS
                ,FULLVISITORID AS PN_FULLVISITORID
                ,DATE AS PN_DATE
            FROM
                TABLE_DATE_RANGE([90303901.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
            WHERE
                REGEXP_MATCH(HITS.APPINFO.SCREENNAME, R'^.*push_type=PUSH_N'))
        ) AS VISIT
        INNER JOIN [durable-binder-547:ZZ_CFM.TAT_PARAMETERMAPPING] AS MAPPING_TABLE ON PN_CAMPAIGNID = PM_PARAMETER
    WHERE
        DATEDIFF(PN_DATE, PN_SENDDT) >= 0
        AND DATEDIFF(PN_DATE, PN_SENDDT) <= 7--配信から7日以内の流入に絞る
        AND PM_CHANNELID = 3--PUSH
        AND PM_CHANNEL_DETAILID = 1--新着
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNELID
        ,VC_CHANNEL_DETAILID
        ,VC_CAMPAIGNID
        ,VC_OSID
        ,VC_FULLVISITORID
    ),
    --パーソナライズPUSH
    (
    SELECT
        PP_VISITTIME AS VC_VISITTIME
        ,PP_SENDDT AS VC_SENDDT
        ,3 AS VC_CHANNELID--PUSH
        ,4 AS VC_CHANNEL_DETAILID--パーソナライズ
        ,INTEGER(PP_CAMPAIGNID) AS VC_CAMPAIGNID
        ,PP_OS AS VC_OSID
        ,PP_FULLVISITORID AS VC_FULLVISITORID
    FROM
        --PUSH_PERSONALIZE/*PREFIX = PP*/
        --iOS
        (SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS PP_VISITTIME
            ,NTH(3, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')) AS PP_SENDDT
            ,NTH(1, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_P', ''), '_')) AS PP_CAMPAIGNID
            ,1 AS PP_OS
            ,FULLVISITORID AS PP_FULLVISITORID
            ,DATE AS PP_DATE
        FROM
            TABLE_DATE_RANGE([90402834.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            REGEXP_MATCH(HITS.APPINFO.SCREENNAME, R'^.*push_type=PUSH_P')),
        --Android
        (SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS PP_VISITTIME
            ,NTH(3, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_', ''), '_')) AS PP_SENDDT
            ,NTH(1, SPLIT(REGEXP_REPLACE(HITS.APPINFO.SCREENNAME, R'^.*PUSH_P', ''), '_')) AS PP_CAMPAIGNID
            ,2 AS PP_OS
            ,FULLVISITORID AS PP_FULLVISITORID
            ,DATE AS PP_DATE
        FROM
            TABLE_DATE_RANGE([90303901.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            REGEXP_MATCH(HITS.APPINFO.SCREENNAME, R'^.*push_type=PUSH_P'))
    WHERE
        DATEDIFF(PP_DATE, PP_SENDDT) >= 0
        AND DATEDIFF(PP_DATE, PP_SENDDT) <= 7--配信から7日以内の流入に絞る
        AND INTEGER(PP_CAMPAIGNID) IS NOT NULL
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNELID
        ,VC_CHANNEL_DETAILID
        ,VC_CAMPAIGNID
        ,VC_OSID
        ,VC_FULLVISITORID
    )