SELECT
    STRFTIME_UTC_USEC(VC_VISITTIME, "%Y/%m/%d %H:%M:%S") AS VC_VISITTIME
    ,STRFTIME_UTC_USEC(VC_SENDDT, "%Y/%m/%d") AS VC_SENDDT
    ,VC_CHANNEL
    ,VC_CHANNEL_DETAIL
    ,VC_CAMPAIGNID
    ,VC_DEVICE
    ,NULL AS VC_OS
    ,NULL AS VC_EMAILID
    ,VC_OFFERID
    ,VC_FULLVISITORID
    ,VC_REVENUE
FROM
    --Pメール_2.0
    (
    SELECT
        MPO_VISITTIME AS VC_VISITTIME
        ,MPO_SENDDT AS VC_SENDDT
        ,PM_CHANNEL AS VC_CHANNEL
        ,PM_CHANNEL_DETAIL AS VC_CHANNEL_DETAIL
        ,PM_MAPPINGID AS VC_CAMPAIGNID
        ,CASE
            WHEN UPPER(MPO_DEVICE) = 'MO' THEN 1
            WHEN UPPER(MPO_DEVICE) = 'PC' THEN 2
        END AS VC_DEVICE
        ,MPO_FULLVISITORID AS VC_FULLVISITORID
        ,SUM(INTEGER(NVL(MPO_REVENUE/1000000, 0))) AS VC_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS MPO_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS MPO_SENDDT
            ,NTH(3, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS MPO_SOURCE
            ,NTH(5, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS MPO_DEVICE--この段階でUPPERをかけるとエラーになる
            ,FULLVISITORID AS MPO_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS MPO_REVENUE
            ,DATE AS MPO_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('2017-11-21'), TIMESTAMP('2017-11-21'))--TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
        WHERE
            TRAFFICSOURCE.MEDIUM = 'mailpersonal'
    ) AS MAIL_PERSONALIZE_OLD/*PREFIX = MPO*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_PARAMETERMAPPING] AS MAPPING_TABLE ON MPO_SOURCE = PM_PARAMETER
    WHERE
        UPPER(MPO_DEVICE) IN ('PC', 'MO')
        AND REGEXP_MATCH(MPO_SOURCE, R'^C[0-9]{9}')--Cから始まるキャンペーンコード
        AND DATEDIFF(MPO_DATE, MPO_SENDDT) >= 0
        AND DATEDIFF(MPO_DATE, MPO_SENDDT) <= 7--配信から7日以内の流入に絞る
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNEL
        ,VC_CHANNEL_DETAIL
        ,VC_CAMPAIGNID
        ,VC_DEVICE
        ,VC_FULLVISITORID
    ),
    --Pメール_3.0
    (
    SELECT
        MPN_VISITTIME AS VC_VISITTIME
        ,MPN_SENDDT AS VC_SENDDT
        ,1 AS VC_CHANNEL--メール
        ,4 AS VC_CHANNEL_DETAIL--パーソナライズ
        ,INTEGER(MPN_CAMPAIGNID) AS VC_CAMPAIGNID
        ,INTEGER(MPN_DEVICE) AS VC_DEVICE
        ,INTEGER(MPN_OFFERID) AS VC_OFFERID
        ,MPN_FULLVISITORID AS VC_FULLVISITORID
        ,SUM(INTEGER(NVL(MPN_REVENUE/1000000, 0))) AS VC_REVENUE
    FROM (
    SELECT
        FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS MPN_VISITTIME
        ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS MPN_SENDDT
        ,NTH(3, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS MPN_CAMPAIGNID
        ,NTH(4, SPLIT(TRAFFICSOURCE.SOURCE, '_')) AS MPN_DEVICE
        ,NTH(2, SPLIT(TRAFFICSOURCE.CAMPAIGN, '_')) AS MPN_OFFERID
        ,FULLVISITORID AS MPN_FULLVISITORID
        ,TOTALS.TOTALTRANSACTIONREVENUE AS MPN_REVENUE
        ,DATE AS MPN_DATE
    FROM
        TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('2017-11-21'), TIMESTAMP('2017-11-21'))--TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
    WHERE
        TRAFFICSOURCE.MEDIUM = 'mailpersonal'
    ) AS MAIL_PERSONALIZE_NEW/*PREFIX = MPN*/
    WHERE
        MPN_DEVICE IN ('1', '2')
        AND REGEXP_MATCH(MPN_OFFERID, R'^[0-9]{1,}')
        AND DATEDIFF(MPN_DATE, MPN_SENDDT) >= 0
        AND DATEDIFF(MPN_DATE, MPN_SENDDT) <= 7--配信から7日以内の流入に絞る
        AND INTEGER(MPN_CAMPAIGNID) IS NOT NULL
        AND INTEGER(MPN_OFFERID) IS NOT NULL--デバイスは1行目で1か2に絞る条件を入れているのでNULLかどうかの条件は不要
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNEL
        ,VC_CHANNEL_DETAIL
        ,VC_CAMPAIGNID
        ,VC_DEVICE
        ,VC_OFFERID
        ,VC_FULLVISITORID
    ),
    --トランザクションメール
    (
    SELECT
        MT_VISITTIME AS VC_VISITTIME
        ,MT_SENDDT AS VC_SENDDT
        ,PM_CHANNEL AS VC_CHANNEL
        ,PM_CHANNEL_DETAIL AS VC_CHANNEL_DETAIL
        ,PM_MAPPINGID AS VC_CAMPAIGNID
        ,MT_FULLVISITORID AS VC_FULLVISITORID
        ,SUM(INTEGER(NVL(MT_REVENUE/1000000, 0))) AS VC_REVENUE
    FROM (
        SELECT
            FORMAT_UTC_USEC(VISITSTARTTIME * 1000000 + 32400000000) AS MT_VISITTIME
            ,LEFT(TRAFFICSOURCE.CAMPAIGN, 8) AS MT_SENDDT
            ,TRAFFICSOURCE.SOURCE AS MT_SOURCE
            ,FULLVISITORID AS MT_FULLVISITORID
            ,TOTALS.TOTALTRANSACTIONREVENUE AS MT_REVENUE
            ,DATE AS MT_DATE
        FROM
            TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('2017-11-21'), TIMESTAMP('2017-11-21'))--TABLE_DATE_RANGE([109049626.ga_sessions_],TIMESTAMP('${ga_start_date}'), TIMESTAMP('${ga_end_date}'))
    ) AS MAIL_TRANSACTION/*PREFIX = MT*/
    INNER JOIN [durable-binder-547:ZZ_CFM.TAT_PARAMETERMAPPING] AS MAPPING_TABLE ON MT_SOURCE = PM_PARAMETER
    WHERE
        DATEDIFF(MT_DATE, MT_SENDDT) >= 0
        AND DATEDIFF(MT_DATE, MT_SENDDT) <= 7--配信から7日以内の流入に絞る
        AND PM_CHANNEL = 1--メール
        AND PM_CHANNEL_DETAIL = 3--トランザクション
    GROUP EACH BY
        VC_VISITTIME
        ,VC_SENDDT
        ,VC_CHANNEL
        ,VC_CHANNEL_DETAIL
        ,VC_CAMPAIGNID
        ,VC_FULLVISITORID
    )